jsonschema-core.xml

Core: Mention alternate media types like CBOR

---

schema.json

Allow boolean schemas everywhere (meta-schema).

---

README.md

For the example of how these will look, take a look at https://github.com/json-schema-org/json-schema-org.github.io

Added label badges to readme.md

---

jsonschema-core.xml
jsonschema-hyperschema.xml
jsonschema-validation.xml

@handrews Can I get your sign-off on this PR's accuracy?

Add Henry Andrews, author

---

jsonschema-hyperschema.xml

Remove stray reference to pre-processing.

---

README.md

Included link to previous versions of the spec

---

schema.json

An integer with a minumum value of 0 is a non-negative integer.

Rename 'positiveInteger' to 'nonNegativeInteger'

---

schema.json

...because "defaultItems" is not actually a thing.
Addresses #260, with thanks to @mspiegel

"defaultItems" should be "default"

---

jsonschema-core.xml
jsonschema-hyperschema.xml
jsonschema-validation.xml

Update release notes after looking through the logs for each file.
@donaldpipowitch, @asds, @bowman: you have all been added under
"Acknowledgements" since you have PRs accepted.  Please comment
if I have your names wrong or you would prefer not to have your
name on the draft.

Update release notes and acknowledgements

---

jsonschema-hyperschema.xml

Also remove what looks like a stray copy-paste of half a sentence.

Fix typos in hyper-schema spec.

---

jsonschema-core.xml
jsonschema-hyperschema.xml
jsonschema-validation.xml

[RFC 7231 section 5.3.1](https://tools.ietf.org/html/rfc7231#section-5.3.1) defines "Quality Values"
[RFC 7231 section 5.3.2](https://tools.ietf.org/html/rfc7231#section-5.3.2) defines the "Accept" header

Correct RFC 7231 "Accept" header section references.

---

jsonschema-validation.xml

Not sure how this got in, but it is breaking the build now.

Fix missing </t>

---

hyper-schema.json
links.json

...and the simultaneous "schema" and "encType" renames.

Update meta-schemas for "method" removal

---

jsonschema-core.xml
jsonschema-validation.xml

Mostly tiny tweaks. One sentence reworded for readability, one wording alteration to exclude a possible misintepretaton.

Several small proofing changes to spec

---

jsonschema-hyperschema.xml
jsonschema-validation.xml

I've asked @epoberezkin to verify that these validate themselves (see https://github.com/json-schema-org/json-schema-spec/issues/206#issuecomment-283751327 )
Once we are certain of that, we can copy them over to the web site repo and merge this change, as discussed in issue #165 
This PR directly addresses #208

Update for new meta-schemas.

---

jsonschema-core.xml

This sentence does not have a main verb.
I didn't notice any contribution guidelines, so I apologize if this isn't the proper way to do this. Submitting a PR in this case was just easier than opening an issue describing the typo. Feel free to close this PR and make the change however you need to :slightly_smiling_face:

Fix sentence fragment

---

jsonschema-validation.xml

This addresses issue #346, where it was not clear whether all
aspects of the core spec were relevant to validation.
@awwright you are probably the most aware of any relevant language subtleties.
Does this change seem reasonable and accurate to you?  I'm not attached to
the exact wording.

Clarify how validation builds off of core.

---

schema.json

I guess we forgot during draft-06?

[trivial] Add "examples" to the meta-schema.

---

jsonschema-hyperschema.xml

Missed a spot!
Change "media": {"type": "..."} to "contentMediaType": "..."

Fix "media" in submission example.

---

jsonschema-core.xml
jsonschema-validation.xml

There are still some open issues and PRs, but this covers everything that has been merged so far for these two specifications.

Changelog in progress for validation and core

---

jsonschema-validation.xml

Thanks to @epoberezkin for spotting.

Fix omitted format in changelog

---

.gitignore
Makefile
relative-json-pointer.xml

This is the best I can manage for reproducing the previous
draft's XML (but adding myself as editor and updating the draft name).
A few of the xref's may be in slightly different styles, as I've
never entirely figured out all of the options for that.  But they
are all equally readable compared to the past generated document
as far as I can tell.
Also add to the Makefile and .gitignore.

Reconstruct the Relative JSON Pointer I-D XML

---

jsonschema-hyperschema.xml

This is just to get the conversation started about this approach
to examples.
Note that the diff is relative to the rewrite.

Rough draft of a few examples

---

jsonschema-hyperschema.xml

Changelog for hyper-schema

---

jsonschema-hyperschema.xml

This is a proposed replacement for the commit removed from #470.

Better wording in HTTP "targetHints" section

---

jsonschema-hyperschema.xml

Use language more in line with recent changes and recently
introduced concepts.  Add a little more detail about the
general capabilities.  This is all roughly inspired by reading
the guidelineson abstracts in RFC 7322 section 4.3

Improve the hyper-schema abstract

---

jsonschema-core.xml
jsonschema-hyperschema.xml
jsonschema-validation.xml

This was approved as PR #489 but I messed up the merge base.  I'll merge this immediately as there are no new changes to review.

Rebase previously approved PR

---

jsonschema-core.xml
jsonschema-hyperschema.xml
jsonschema-validation.xml
relative-json-pointer.xml

Copy G. Luff's from the relative pointer spec, and add mine.
[Another mechanical change that I will merge if the build completes successfully]

Add postal addresses

---

CONTRIBUTING.md

* Explain current issue, milestone, and PR process
* Explain how I-Ds may be published without a new meta-schema
* Explain how meta-schemas may be updated in place
* We do not keep the "master" branch publication-ready, aside
from how it should always build and therefore could techncially
be submitted.  But the paragraph made it sound like "master"
should make sense as a publishable draft which is definitely
not always the case.

Update CONTRIBUTING.md for current practices

---

jsonschema-core.xml
jsonschema-hyperschema.xml
jsonschema-validation.xml
relative-json-pointer.xml

This needs to be done for the files to build.

Update to 2018

---

jsonschema-core.xml
jsonschema-hyperschema.xml
jsonschema-validation.xml

Addresses #527, plus draft numbers and author affiliations (in a separate commit).

JSON RFC update, fix draft numbers, update affiliations

---

hyper-schema.json
schema.json

Which has apparently been wrong the whole time.
Also fix minor formatting inconsistencies.

Fix propertyNames meta-schema (curent master)

---

hyper-schema.json
schema.json

But keep "contains" which really was missing.

[draft-06] Reverse incorrect "propertyNames" change

---

hyper-schema-output.json

This proposed file change addresses https://github.com/json-schema-org/json-schema-spec/issues/639 and https://github.com/json-schema-org/json-schema-spec/issues/641.

Fixing #639 and #641

---

schema.json

This fixes up the meta-schema for PR https://github.com/json-schema-org/json-schema-spec/pull/525.

Add min-/maxContains to meta-schema

---

jsonschema-hyperschema.xml

Addresses #543, to the extent that I think we should address it.
This is a common question, so make a note of it where we
introduce link validity.  There are some other ways of doing
this like "templateRequired" which I think are already covered
well enough.  A higher-level guide on various techniques is,
I think, outside the scope of the specification.

Add a bit about conditional links

---

jsonschema-core.xml

In the phrase, "in some circumstance", the word "circumstance" ought to be pluralized.

Fix typo/grammar mistake in "Keyword Behaviors"

---

jsonschema-hyperschema.xml

This matches "targetHints", and resolves #676 in the most minimal way possible.

"headerSchema" should use array values

---

schema.json

This seems to already appear in Draft 7.

Add in the missing check that patternProperties are regexen.

---

.travis.yml

Update xml2rfc required version

---

jsonschema-core.xml
jsonschema-hyperschema.xml
jsonschema-validation.xml
relative-json-pointer.xml

Just some last pre-final-review details.

Add change logs and update my contact info

---

hyper-schema.json
jsonschema-core.xml
jsonschema-hyperschema.xml
jsonschema-validation.xml
links.json
meta/applicator.json
meta/content.json
meta/core.json
meta/format.json
meta/hyper-schema.json
meta/meta-data.json
meta/validation.json
output/hyper-schema.json
output/schema.json
schema.json

This is a re-open of #799 which shouldn't have been merged yet due to how all of the current open PRs are stacked.
Note that @Relequestual already approved #799, so this doesn't really need to be re-reviewed although feel free :-)

Update meta-schema dates, minor changelog typo

---

jsonschema-core.xml

[912] Fix trailing comma in "Output Structure" example instance

---

output/schema.json

Fix a raw "$" in two patterns and add a missing "$defs" in three paths

Fix patterns and paths in output schema

---

meta/applicator.json

[900] Add missing "type" to applicator meta-schema

---

output/verbose-example.json

this corrects an oversight from the changes made in #938.

fix verbose output example with json-pointer replacing uri-reference

---

jsonschema-core.xml

If no one objects soonish I'll merge this trivial PR myself.

Remove trailing whitespace

---

jsonschema-core.xml

Typo in jsonschema-core.xml dialec for dialect

---

jsonschema-core.xml

"idenfity" for "identify", "unevaluted" for "unevaluated"

Two typos in jsonschema-core.xml

---

jsonschema-core.xml

[1010] Remove duplicate words

---

output/schema.json

resolves #1014 - update output schema for draft 2020-xx

---

jsonschema-core.xml

Made it clearer that the value of $schema is a dialect identifier,

Replace the phrase "feature set" with dialect

---

jsonschema-core.xml

add paragraph describing independence of sibling subschemas

---

jsonschema-core.xml

[1036] Add a missing "a"

---

jsonschema-core.xml

Resolves #1032 
There may be valid reasons to place embedded schema resources in other locations.

Reduce restrictions on where bundled schema resource may be located

---

jsonschema-core.xml

Also fixes the "validates" tense to match the first use.
Fixes #1043

[1043] Clarify last paragraph in "contains" section

---

jsonschema-core.xml

Fix incorrect stipulation on keyword ordering for unevaluated* keywords.

---

jsonschema-core.xml

Somehow I missed this during the earlier review! :o

fix example of Keyword Relative Location

---

links.json

Fix bug found by @karenetheridge https://github.com/json-schema-org/json-schema-spec/issues/1120#issuecomment-963552245

Fix $schema for links.json

---

schema.json

fix broken reference

---

README.md

Add README instructions on how to install xml2rfc

---

Makefile

Looks like this one has been missed.

Add the "all" target to the list of PHONY targets

---

adr/2022-04-08-cref-for-ambiguity-and-fix-later-gh-spec-issue-1172.md

Resolves https://github.com/json-schema-org/json-schema-spec/issues/1221

Improve readability for ADR

---

jsonschema-core.xml
jsonschema-validation.xml

Specifically draft-bhutton-json-schema-01 and draft-bhutton-json-schema-validation-01

Add changelog for 2020-12 patch 1 release documents

---

jsonschema-validation.xml

Resolves #1221 remaining issues.

add clarification that minContains:0 also causes contains to pass

---

.github/workflows/ci.yml

actions/glob doesn't appear to support |.
See https://github.com/actions/toolkit/tree/main/packages/glob#glob-behavior

Fix artifact upload patterns.

---

hyper-schema-output.json

Partial fix for https://github.com/orgs/json-schema-org/discussions/330

Fix hyper-schema output schema id

---

relative-json-pointer.xml

Applies @eemeli's suggestion from [here](https://github.com/json-schema-org/json-schema-spec/pull/1400#discussion_r1189201589)
Given that this suggestion was made two weeks ago and approved, I'm planning on merging this sooner than the two week restriction.

update abnf per @eemeli suggestion

---

jsonschema-core.xml

fix regex in example meta-schema with custom vocab

---

jsonschema-core.xml
jsonschema-validation.xml

I am aware that the format is changing and there are multiple PRs open for those changes.  It doesn't matter to me whether this particular PR is merged or not as long ad the spirit of the changes carry forward to whatever future publications are made.

Move myself from current to past author list

---

README.md

Fixes https://github.com/json-schema-org/json-schema-spec/issues/1454

Fix link to 404 in readme

---

meta/applicator.json
meta/content.json
meta/core.json
meta/format-annotation.json
meta/format-assertion.json
meta/meta-data.json
meta/unevaluated.json
meta/validation.json

Relates to [Discussion #511](https://github.com/orgs/json-schema-org/discussions/511).

remove `$vocabulary` from vocab meta-schemas

---

meta/applicator.json
meta/content.json
meta/core.json
meta/format.json
meta/hyper-schema.json
meta/meta-data.json
meta/validation.json

Relates to [Discussion #511](https://github.com/orgs/json-schema-org/discussions/511).

remove `$vocabulary` from vocab meta-schemas (2019-09)

---

README.md

Refs: json-schema-org/website#201

Update the link to the JSON Schema website.

---

README.md

Refs: json-schema-org/website#201

Update the link to the JSON Schema website for 2020-12.

---

README.md

Refs: json-schema-org/website#201

Update the link to the JSON Schema website for 2019-09

---

README.md

Refs: json-schema-org/website#201

Update the link to the JSON Schema website for draft 07

---

jsonschema-use-cases.xml
relative-json-pointer.xml

Just updating dates to fix the build.

update RJP 2023 to 2024

---

jsonschema-validation.md

fixing https://github.com/json-schema-org/json-schema-spec/issues/1356

Update jsonschema-validation.md - fix Typo

---

output/schema.json

per
https://github.com/json-schema-org/json-schema-spec/issues/1347
https://github.com/json-schema-org/json-schema-spec/pull/1351

Update validation output format schema `nested` to `details`
