jsonschema-core.xml, jsonschema-schema.xml
The only "non interactive" without hyphenation I have left in is the title of an earlier publication.
=> Standardise use of hyphens with 'non'

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-schema.xml
I discovered recently that the usage of the `profile` Accept header extension
described in the documentation is not a valid accept header extension.
```
Content-Type: application/json; profile=/schema-for-this-data
```
The schema should be within quotes in order the valid.
```
Content-Type: application/json; profile="/schema-for-this-data"
```
This is how the `Content-Type` header is defined
```
Content-Type   = "Content-Type" ":" media-type
media-type     = type "/" subtype *( ";" parameter )
type           = token
subtype        = token
parameter      = attribute "=" value
attribute      = token
value          = token | quoted-string
token          = 1*<any CHAR except CTLs or separators>
separators     = "(" | ")" | "<" | ">" | "@"
| "," | ";" | ":" | "\" | <">
| "/" | "[" | "]" | "?" …
```
=> `profile` in Accept header must be a quoted-string

jsonschema-core.xml, jsonschema-hyperschema.xml
So let's try making a pull request to the draft.
Not to push things along faster than they must, of course, let's be sure of the PR model we want to use before merging.
---
This fixes a number of vocabulary confusion, and inconsistencies with the URI definitions and ABNF terms. I think there's still a few more, though.
=> s/resolution scope/base URI/

jsonschema-core.xml, jsonschema-hyperschema.xml
Fix for Issue #24
JSON Pointer graduated from draft status to proper RFC a while back.
=> Update JSON Pointer xref to RFC

jsonschema-hyperschema.xml
Remove some stray words that somehow found their ways into the wrong sentences.
Fixes old repo issues (filed by vanthome):
https://github.com/json-schema/json-schema/issues/89
https://github.com/json-schema/json-schema/issues/100
=> Fix typos in Hyper Schema spec.

schema.json
Fixes old repo issues:
https://github.com/json-schema/json-schema/issues/84
https://github.com/json-schema/json-schema/issues/198
Previously submitted to the old repository by IvanGoncharov as commit 472c32b
and pull request #163 with original comment:
Added validation according to
http://json-schema.org/latest/json-schema-validation.html#anchor105
Merged into the old repo by geraintluff on May 8, 2015.
=> Add "format" validation to the meta-schema.

jsonschema-core.xml
Addresses #9, #26 
Rendered draft available at [jsonschema-core.txt](https://github.com/json-schema-org/json-schema-spec/files/466582/jsonschema-core.txt)
=> Rewrite/expand HTTP/profile/describedby sections

jsonschema-validation.xml
This is a fix for #103 , although I went a bit further and made an effort to make all of the object/array property/item keywords consistent.  I expect the wording might need a bit of tweaking even if the general approach is accepted.  Also, I'll happily drop this if a different approach is preferred.
Separate "items" and "additionalItems" for consistency with the separate "properties",
"patternProperties", and "additionalProperties".
Fix wording bug:  non-objects always successfully validate against "additionalProperties".
Arrange the wording for each of these to follow this pattern:
- keyword value type requirements
- value to assume if absent (if relevant)
- validation against the instance (independent of child validation)
- validation of children (possibly first explaining to which …
=> Make properties/items wording consistent.

jsonschema-validation.xml, schema.json
This addresses the enhancement requested in issues #32 and #63.
Only the single-schema form from #63 is added here as the multi-schema form
did not gather significant support in the absence of a clear use case.
=> Add the "contains" keyword for array instances.

jsonschema-validation.xml, schema.json
This addresses the enhancement requested in issue #69.
=> Allow an empty array for "required".

hyper-schema.json, schema.json
These changes were made for draft 05 but as that was intentionally published
with no new meta-schema, we are going straight to draft 06 with the
meta-schema identifiers.
=> Update meta-schemas for changes in the last draft.

jsonschema-hyperschema.xml
This addresses issue #97, where it was noted that "The only
interpretation that makes sense is it's providing an array
of instances, each can be described by the schema."
This makes the schema an array schema, and replaces the "self"
link with the more correct (or at least less confusing in this
context) "item" link.
Also fix a "the the" typo in the security considerations section,
and make "hyper-schema" consistent.
=> Fix parent link example.

jsonschema-validation.xml
=> Validation: Fix reference to seven primitive types

jsonschema-validation.xml, schema.json
This addresses issue #58, which got quite a few upvotes and has
a "draft 6" milestone.
I used the shorter "const" that several people suggested rather
than "constant", but obviously that's easy to change if the longer
form is preferred.
The wording was pretty much directly lifted from "enum".
=> Add "const" keyword for constant values.

jsonschema-validation.xml
This addresses issue #121.
Most of the wording is lifted from "default", which is similar and can serve
the same purpose.  This wording explicitly allows for using "default" as an
example which was not part of the original request but seems reasonable.
Obviously, that part can be removed if deemed undesirable.
=> Add the "example" keyword.

jsonschema-validation.xml
In #135 the question of whether additionalItems could fail validation
if items is not defined was raised.  Since items defines a default
value of {}, it is never undefined, which is clarified in this change.
=> Clarify "items"/"additionalItems" interaction.

jsonschema-hyperschema.xml, jsonschema-validation.xml
The current drafts don't actually list a meta-schema URI.
Previous drafts listed a URI in "core", but this was effectively the same thing.
Add a note until we figure out how to publish the meta-schema.
=> Add note about current meta-schema URIs

jsonschema-core.xml, jsonschema-validation.xml
This implements issue #101, including root schemas.
@awwright requested this form of the solution to compare against PR #128,
which only defines booleans for subschemas.  The idea is that it is sometimes
useful to have an entire schema which always passes or always fails, and
the idiom should be the same everywhere.
Note that with [RFC 7159](https://tools.ietf.org/html/rfc7159#section-2),
the restriction that JSON documents could only be arrays or objects
was removed, so a single boolean value is a valid JSON document.
I slightly prefer this to PR #128, myself.
Also add JSON Reference objects as legal schemas in the meta-schema.
Since "$ref" is now only allowed as a JSON Reference where a schema
is acceptable, it can now be described in JSON Schema and included
in the "anyOf" that defines …
=> Allow boolean schemas everywhere (root and subschemas)

jsonschema-validation.xml
Addresses issue #109 by adding "uritemplate" and "jsonpointer",
as defined by their RFCs, both of which already play roles
within JSON (Hyper-)Schema.
We use "uritemplate" in hyper-schema, but until the preprocessing
step is removed we technically can't put the format in the
meta-hyperschema.  This is being addressed elsewhere
(#142 and #129 propose one possible approach).
While we do not need "jsonpointer" for our meta-schema, it is
used for schema+json URI fragments, and in other JSON-based
media types such as JSON Patch.
=> "uritemplate" and "jsonpointer" formats

jsonschema-core.xml
The value of "$schema" is not required to be an absolute URI
as defined by RFC 3986 (with a scheme, but no fragment).  It just
needs to be a URI and not a relative reference.
This is particularly important as the meta-schemas include
an empty fragment in their id URIs, which would be illegal if
RFC 3986 section 4.3 Absolute URIs were required.
=> Remove confusing use of "absolute" URI.

hyper-schema.json, links.json, schema.json
This brings formatting and most of the initial field ordering
in line with the Draft 05 meta-schemas proposed in the web site
repo.
Also ensure that hyper-schema's definition of "schemaArray"
cannot get out of sync with schema's, and add the link schema.
=> Standardize format of meta-schemas.

hyper-schema.json
This brings it in line with the core/validation meta-schema and
with the standardized format proposed for Draft 05.
=> Move hyper-schema definitions to top.

jsonschema-validation.xml, schema.json
=> Validation: Add "propertyNames" keyword

jsonschema-validation.xml
These are the leftover bits of Issue #55 and some clarifications
requested in a comment on issue #101 that have not already been
added in some other PR for some other issue.
These specific chagnes were previously approved in #143, but so
many other things have changed since #143 that most of it was
no longer relevant, so I closed it and started these changes over.
In particular, explaining {} and {"not": {}} is no longer needed
as they are covered while introducing "true" and "false" schemas
in the core specification, so that is no longer included in this
change.
Likewise, the parent/child validation descriptions have been
modified in several PRs and no longer has the problems that were
previously a concern.
=> Wording clarifications in general considerations.

schema.json
@handrews @awwright An alternative to #194, other changes seems to be merged already
=> schema for $ref keyword

hyper-schema.json, jsonschema-core.xml, links.json, schema.json
This addresses issue #20.  It is an alternative to PR #154.
"$id" matches "$schema" and "$ref", establishing a clear naming
pattern for all keywords defined in the core specification.  This
also reduces confusion in the very common case where objects
described by the schema have an "id" property.
=> Change "id" to "$id" to match other core keywords

jsonschema-validation.xml, schema.json
Also, be clear about the defaulting in the description for "required".
This comes from https://github.com/json-schema-org/json-schema-spec/issues/69#issuecomment-262079319
=> String arrays default to empty.

jsonschema-hyperschema.xml
"mediaType" is an LDO keyword.  The keyword in the "media" object
is just plain "type".
=> Correct "mediaType" to "type" in example.

hyper-schema.json, jsonschema-hyperschema.xml, links.json
[EDIT:  This PR now **does not** remove "method", nor does it drop "href" preprocessing]
This introduces "hrefSchema" which provides a schema for user input
matching the "href" URI Template variables.
The meta-schemas have been updated accordingly.
---
Here are some examples (note that "method": "get" is the default, but is included for clarity):
Here is a Draft 05 "get" with parameters:
```JSON
{
"href": "/examples",
"method": "get",
"encType": "application/x-www-form-urlencoded",
"schema": {
"properties": {
"name": {"type": "string"},
"whatever": {"type": "number"}
}
}
}
```
Here is the equivalent using "hrefSchema" (note "name" and "whatever" in the URI Template).  It is not necessary to specify "x-www-form-urlencoded" here, as the "{?name,whatever}" form of URI template variable …
=> Support URI input with "hrefSchema"

hyper-schema.json, jsonschema-validation.xml, links.json, schema.json
When we had more formats in earlier drafts, all compound names
(such as "date-time") were hyphenated.  Draft 05 added "uriref"
without a hyphen, which started looking weird when we added
"uritemplate" and "jsonpointer" without hyphens to match it.
This makes everything hyphenated (note "hostname" was deemed
to be a single word in this context).
Addresses issue #207.
=> Standardize on hyphenated format names

jsonschema-validation.xml
This implements suggestions from @deuberger discussions in issue #161.
=> Improve child validation wording from feedback.

jsonschema-core.xml
=> Core: Restrict usage of $schema some

jsonschema-hyperschema.xml
This documents the assumptions I have found myself forced to
make while writing a generic hyper-client.  There are other workable
assumptions so the exact form (and the use of MUST vs SHOULD)
is open to debate.
It's been commonly assumed that hyper-schema keywords apply only
when validation is successful.  Be explicit about this, and resolve
ambiguous situations.
Most notably, remove any burden on implementations to figure out
what to do with situations such as:
{"not": {"not": {"links": [...]}}}
where the schema containing links technically must validate against
the instance, but any less trivial nesting of "not"s
(including such situations as a "not" inside of a "oneOf" branch
that fails validation while the overall "oneOf" succeeds) rapidly
becomes extremely difficult to reason about.
=> Provide guidance on hyperschema and validation

jsonschema-validation.xml
The formats all had these subsections in an earlier draft but they
were removed, which was a good thing.
Apparently "hostname" was overlooked in the removal.
=> Remove subsections for "hostname" format.

jsonschema-core.xml
This addresses issue #243. (edit: and #144)
Reference the JSON Pointer RFC for using JSON Pointers
as fragids (includes encoding requirements).
Remove the syntax description for how to write a fragment
URI reference (leading "#") as that is covered by RFC 3986.
Also fill in a bit more of the IANA considerations section.
=> Clearly define schema+json fragid forms.

hyper-schema.json, links.json, schema.json
We are not using "latest"-style URIs anymore.
schemaArray in hyper-schema is intended to reference the schemaArray
in schema and just "allOf" the hyper-schema {"$ref": "#"} into the "items".
Addresses https://github.com/json-schema-org/json-schema-spec/issues/206#issuecomment-283775164
=> Add meta-schema version numbers, fix reference.

hyper-schema.json
"id" became "$id", and we handle "$" through percent-encoding
URI Templates reserve "$", but do not specify how percent-encoding
is to be used, except that implementations should be consistent about
it.  We document that we always percent-decode variables before
resolving them.
=> Fix hyper-schema meta-schema self link.

jsonschema-hyperschema.xml
We removed the preprocessing rules, including those related to
using the entire instance value, and made a note of the limitation
and intent to remove it in a future draft.
This stray phrase should have been removed at that time.
Also add a cref acknowledging the limitations and further work
needed in this area.  There was such a cref in the previous
draft and I had thought I'd updated it rather than deleting it,
but apparently not.  It was a good idea, let's keep it.
=> Remove leftover wording from preprocessing, restore limitation note

jsonschema-core.xml, jsonschema-hyperschema.xml
Removing a stray comma, and fixing "imgDataPng" to be "imgData",
which is the name by which it is called multiple times in the
surrounding text.
Also, all examples are camelCase except for "next_id", so I switched
it to "nextId" for consistency.
All examples now parse correctly as JSON, and as far as I can tell
match the surrounding text (although I did just kind of skim for
that part).
=> Example JSON bugfixes

jsonschema-hyperschema.xml
This keeps coming up, and I believe that this clarifies the existing
behavior (vs, say, using "schema" to describe PATCH input).
As with the previous pull request, this is appropriate for
draft-wright-json-schema-hyperschema-01 (Draft 06) if and only if
it is agreed to be a clarification rather than a change.
=> Explain "targetSchema" and HTTP PATCH.

jsonschema-hyperschema.xml
**_This PR need not necessarily go into Draft 06_**
I'm posting this mostly to illustrate some of the arguments in #280, particularly around avoiding coupling of JSON Hyper-Schema and any particular URI scheme or protocol.
If we can't figure out a reasonable mapping for `mailto:` then we might be missing something.  Although that something will probably need to wait until Draft 07 for a fix.
I am aware that it's more common to use an HTTP request to ask the server to send mail, but I think this still makes a good example.  If the client for this resource runs in a known environment, it could be reasonable to expect the client to send mail if it wants to.
---
Add an example showing how a non-HTTP URI scheme can be used,
showing a form for constructing an email with two different …
=> Add non-http "method": "post" LDO example

jsonschema-hyperschema.xml
This addresses part of the compromise reached in #280.
These "schema" keyword is too generic of a name given that
there are now three schemas involved in an LDO.  Change it to
indicate that it is used for submitting data for processing,
as is done with HTML form submissions.
Rename "encType" to match.
=> Prefix "schema" and "encType" with "submission"

jsonschema-hyperschema.xml
***NOTE:  Review this with whitespace changes turned off!!!***
https://github.com/json-schema-org/json-schema-spec/pull/292/files?w=1
This has been split out from #290.  It should not be merged without also
resolving the other parts of that larger change somehow, which will
likely restore some reference to HTML forms.
-----
The feedback to draft-wright-json-schema-hyperschema-00 and from
the final review for draft-wright-json-schema-hyperschema-01
has made it clear that "method" is extremely confusing, and no
two people can agree on the correct usage.  The only clear
impulse is to use the draft-luff-json-hyper-schema-00 meaning
(explicit specification of HTTP methods), which is not the
desired approach.
"method" is not actually necessary now that "hrefSchema" and
"submissionSchema" have …
=> Remove "method" and analogies to HTML forms.

jsonschema-hyperschema.xml
At the beginning of hyperschema document, there's:
> The terms "schema", "instance", "property" and "item" are to be interpreted as defined in the JSON Schema core specification.
but core specification does no longer defines "property" and "item" (from 3cbfc8bcab58ce6c0397f205534d2a4cede76ce8 AFAICT). I guess the former is assumed by JSON terminology; the latter may be confusing w.r.t. to collection+item terminology that appears in sections about links. So removing both references.
=> hyperschema: remove obsolete references to core terminology definitions

jsonschema-hyperschema.xml
***IGNORE the first commit, it is from PR #292***
Review this commit here: https://github.com/json-schema-org/json-schema-spec/pull/293/commits/af5ef3a9c98618ec34906d5e409562baa2cc9451
---
This replaces the rather lengthy discussion of hrefSchema
with a more concise and complete description of all of the
ways to use data with links.  This should now serve to set
the context for the various ways to use LDOs.
=> Rework the descriptions of using data with links

jsonschema-validation.xml
The documentation for "contains" appears to contradict `schema.json`; it says:
> The value of this keyword MUST be an object.  This object MUST be a valid JSON Schema.
However, `schema.json` refers to the root schema, which may be object or boolean.
It seems simplest to say:
> The value of this keyword MUST be a valid JSON Schema.
While `"contains": true` seems to me to have little value, given the general approach that `true` is a schema equivalent to the empty schema `{}` and `false` is a schema equivalent to `{ "not":{} }`, making this an exception to the overall rule seems an unnecessary burden, and I suspect it is an oversight.
=> Allow booleans in "contains" per schema.json

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
As mentioned in https://github.com/json-schema-org/json-schema-spec/issues/206#issuecomment-292872393, to hopefully make future review easier.
I choose 100 columns as a compromise because wrapping to 80 columns would lead to narrow blocks of text for deeply nested elements.
I could not find a tool to automate this that gives satisfactory results so I did that by hand. I occasionally left some text exceed the limit when it looked better not wrapped (e.g. to avoid breaking links).
`git diff --word-diff master` can be used to get a relevant diff.
=> Reformat XML documents to 100 columns length

CONTRIBUTING.md
**NOTE:  Since this wording is identical to our existing policy on the wiki, commentary on the contents will be ignored.  This is just about moving things into the file unchanged.  We can debate changing contents with additional PRs.  That is part of the point of moving this into the repo instead of the wiki.**
This file has exactly the contents of the front wiki page, except
for the I-D and meta-schema publishing processes which are not
relevant to most contributors.
I'm moving it into a CONTRIBUTING.md as it integrates with
GitHub's tools (e.g. auto-linking it to the create PR screen)
and will allow us to discuss changes as PRs.
I will change the front wiki page to link to this (but retain
the sections that have not been moved here).
=> Start a contributing guide from the wiki contents.

jsonschema-hyperschema.xml
Despite having a whole section describing how hyper-schema
builds on validation, it was never referenced or listed
as a normative specifciation.
Also, we had labled the meta-schema link as a validation schema
in an apparent copy-paste error.
Finally, improve wording around building on the other specs in
the same way as was done for the validation spec referincing core.
=> Reference validation from hyper-schema

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
None of the open PRs have a change log, because they would
all conflict with each other.  This initializes empty change
logs and updates the draft numbering accordingly.
Note that there must be at least an empty <t></t> in the list
or the XML won't validate against its DTD.
Ensuring that the entire changelog is filled out is part of
the pre-publication checklist.
=> Set up a blank change log for the next draft.

jsonschema-validation.xml
**NOTE:** This diff should be viewed [with whitespace ignored](https://github.com/json-schema-org/json-schema-spec/pull/357/files?w=1)
This improves the readability of the spec, particularly
new readers trying to get a feel for the scope from the
table of contents.
A previous, more complex reorganization that was attempted
before got plenty of support, and this more minimal change
avoids the issues that bogged the previous approach down.
Finally, having sections will make the section grouping
"if", "then", and "else" (#180) make more sense.  Adding those
keywords without grouping them would seem odd.
=> Split validation keywords into sections.

jsonschema-validation.xml
Addresses issue #328.  URI fragment-encoded JSON Pointers are
already handled by the "uri-reference" format, plus "pattern"
if the media type supports multiple fragment types that would
need to be disambiguated.
Guidance on using "uri-reference" plus "pattern" belongs on
the web site, so I did not add it to the spec.
=> Clarify what is meant by JSON Pointer format.

jsonschema-core.xml, jsonschema-hyperschema.xml
Two very minor fixes that I'd included in the link context trial balloon.  These aren't related to the bigger philosophical change in that PR.
=> Minor readability / clarity fixes

hyper-schema.json, jsonschema-hyperschema.xml
Addresses the simpler half of #140.
This corresponds directly to the RFC 5988 "anchor" keyword.
I'm not sure whether all of the talk of the context URI and whether it is possible
to construct one belongs where I put it in the `"rel"` section or whether it should
be moved to `"anchor"`, or a bit of each.
I'm also not sure if there needs to be more explanation of `"anchor"`.  Since it is
adapted from RFC 5988 I went with less explanation.
=> Add "anchor" LDO keyword.

hyper-schema.json, jsonschema-hyperschema.xml
This addresses issue #325.  It adds the description keyword,
analogous to "description" in validation schemas.  In RFC 5988bis
parlance, "description" is an extension target attribute.
=> Add "description" as an LDO keyword.

jsonschema-core.xml
This addresses the original question posed in #86, which
noted that simply saying that meta-schemas can be extended
with "allOf" is misleading and likely to lead to errors.
=> Highlight the challenges of extending meta-schemas

hyper-schema.json, jsonschema-core.xml, schema.json
This addresses issue #197.  The primary purpose is to reserve the
keyword and ensure that implementations do NOT do anything based
on its presence or contents.  This improves interoperability by
ensuring that comments are safe for use with any conforming system.
Without this keyword, two implementations may implement it with
differing semantics, potentially producing undesirable or
insecure behavior.
Effort has been made to ensure that existing implementations
that properly ignore unknown keywords will not need to make
any changes at all to be in conformance for this keyword.
I noticed while adding $comment that keywords are always quoted
in section headings unless the keyword is the entire heading.
This is true across all three specifications, so the trivial
second commit brings the only …
=> Add "$comment" as a keyword

jsonschema-hyperschema.xml
Format the one we have better, and also explain how using
both instance data and describing client input is analogous
to common interactive form usage.
This is a response to #288, in that it is an attempt to explain
why these features work as they do.  The discussion there
has not produced any alternative that solves the use case
added here (defining input conditions with schemas, but
allowing the existing data to remain unchanged if no
action is taken- identical to pre-populating HTML form
input widgets with "value").
If @jdesrosiers comes up with such a proposal, we will
definitely consider that.  Otherwise, I am asking reviewers
to approve this if they feel that the given use cases justify
the current behavior.
=> Clarify various usage scenarios for URI templates

jsonschema-validation.xml
Follow-up on discussion in #357 by moving "generic" keywords before more specific ones, and then moving the "type" keyword before other ones in its section.
No content change.
=> Reorganize validation keywords

hyper-schema.json
- Fix recursion to cover `contains` (specifically mentioned in section 3.1 of the hyper-schema spec), and `propertyNames` (probably irrelevant, since none of the hyper-schema fields would apply, but feels like a better practise since the core spec refers to the hyper-schema definition for guidance on recursion when extending schemas (see also #86)) 
- Much more concise definition of recursion.
=> Fix recursion in hyper-schema.json

hyper-schema.json, jsonschema-hyperschema.xml, jsonschema-validation.xml, schema.json
This addresses #180.
I have intentionally allowed for any combination of these
keywords to be present or absent.  While having a "then" or "else"
without "if" is pointless and/or nonsensical, so are many other
possible JSON Schema keywords.
=> Specify "if", "then", and "else"

hyper-schema.json, jsonschema-hyperschema.xml, jsonschema-validation.xml, schema.json
This addresses part of #363, which states that some keywords historically in the Hyper-Schema specification would be better in the Validation document. The main argument for moving keywords such as "readOnly" is that the Hyper-Schema document could then only focus on describing the hypermedia linking model.
The second commit fixes the default value of `readOnly` (wrong type).
=> Move "readOnly" from Hyper-Schema to Validation

jsonschema-validation.xml
RFC 2373 has long since been obsoleted, and its replacement has
likewise been obsoleted.  RFC 4291 is the current RFC.  While there
is a further RFC providing recommendations for consistent formatting
of ipv6 addresses, it includes the requirement that all implementations
MUST support the full syntax laid out in RFC 4291, so that is what
we give as the reference.
=> Update ipv6 RFC reference.

hyper-schema.json, links.json
Reboot of #402 splitted into atomic commits.
* use "links" meta-schema in hyper-schema;
* remove all descriptions (addressing #175);
* updates in "links" to fix "$ref" and add missing keywords.
=> meta schemas cleanup: remove descriptions, use and update "links.json"

jsonschema-hyperschema.xml, links.json
This is a very tentative first pass to get the discussion started.
This addresses half of #296, specifically advertising information
about the target that would likely be discovered through mechanism
such as the headers of an HTTP HEAD and/or OPTIONS response.
The half for describing request header (or analogous) data will
be posted separately after we see how this goes.
The goal for this draft is to specify this well enough to get
real-world implementations and feedback.  It seems best to
approach that goal by providing loose guidelines and encouraging
experimentation.
The lack of a standard way to advertise HTTP method support,
for instance, is a ***major barrier to adoption for many who have
expressed interest in Hyper-Schema***.
This draft needs to include an approach that will at …
=> Add "targetHints"

hyper-schema.json, jsonschema-hyperschema.xml, jsonschema-validation.xml, schema.json
Addresses the other part of #363 (see also #378) by moving the "media" keyword into the validation document and splitting it into "contentEncoding"+"contentMediaType" in a (new) dedicated section similar to the one about "format".
All references to "multimedia" are also removed from the Hyper-Schema document. I kept most of the original textual content and examples as a first step.
=> Moving "media" into validation (as "contentEncoding"+"contentMediaType")

jsonschema-validation.xml
This was discussed in the if/then/else issue.  There was significant
support for removing "dependencies" as it is more straightforward,
although sometimes more verbose, to implement the same funcitonality
with if/then/else.
Rather than going straight to ripping it out, let's give if/then/else
a bit of time to gather feedback.  Make a note of it to warn that
"dependencies" may be removed, which will hopefully provoke some
feedback on that idea as well.
=> Note that we may remove "dependencies"

links.json
We just removed all descriptions in 0b0681c; that one slipped in when
PR #383 got rebased (and merged).
=> Drop "description" of targetHints in links.json

jsonschema-hyperschema.xml, links.json
This will need a bit more work after "anchor" (#352) is merged in,
as the improved wording about what the default context is
is all in that other PR.  But the key points are well enough
developed for review.
In the interst of getting the main points out for review, I
referenced the long-expired Relative JSON Pointer I-D.  Maybe
that's OK since this is not even a working group document yet,
or we can talk about how to either move the relevant parts in,
or re-submit that I-D ourselves as well.
This goes along with "hrefPointers" ( #386 ), which adjusts template
variable resolution in the same way that this keyword adjusts
context location.
=> Add "anchorPointer" for in-instance contexts

jsonschema-hyperschema.xml, links.json
This is a companion to "anchorPointer" (#385), as they use the same
mechanism for adjusting locations within the instance.  While
"anchorPointer" adjusts the context, "hrefPointers" adjust
how template variables are resolved.
"hrefPointers" replaces and is much more functional than the
preprocessing rules that were removed in draft wright-01.
Those rules only allowed adjusting to use the sub-instance
as a whole intead of individual properties or elements.
"hrefPointers" supports that as well as using data from
any containg or sub-instance.
=> Add "hrefPointers" for adjusting resolution

jsonschema-hyperschema.xml, links.json
This addresses the request half of #296, and is a companion
keyword to "targetHints" (#383).
Like "targetHints", this is a rough first pass to get the
discussion of specifics started.  I expect it to be somewhat
underspecified to encourage experimentation.
I intentionally chose an example that is both very complex
and very useful.  It might also be worth putting up a simpler
example.  Although when this appears right after "targetHints",
the simpler header value examples in that section will help
motivate what is going on here.
=> Add "headerSchema"

jsonschema-hyperschema.xml
Addresses #297 
There are two commits here: the first simply makes "rel" required, while
the second attempts to address concerns over having to create new URIs
for custom link relations by pointing out two simple approaches.
The `"rel"` section is getting large, but I will address that when I address
#377 in which I have suggested a new outline to more clearly organize
the spec.
RFC 5988bis lists the link relation type as one of the three
required aspects of a link.
Since we do not need to support the deprecated "rev" mechanisms
for specifying relation types, we can make "rel" required.
This will encourage hyper-schema authors to think more about
choosing relation types.
=> Make "rel" required.

jsonschema-hyperschema.xml
RFC 6906 is the "profile" link relation; RFC 6901 is JSON Pointer.
=> Fix JSON Pointer RFC (6901, not 6906).

jsonschema-validation.xml
This addresses #199 by supporting the two least controversial and
most requested addtional date/time formats, and reserving the
remaining namespace while we decide whether or how to specify
additional RFC 3339 formats.
=> Support date and time, and allow for more RFC 3339

jsonschema-validation.xml, schema.json
Addresses #392.  It's come up several times that removing
this format did not make sense and was quite possibly an accident.
The "regex" format was actually still in use in the meta-schema
for "pattern".  I've added it to "patternProperties" as well
using "propertyNames".
Regular expressions are a fundamental programming tool, and
play a part in JSON Schema's specification.  It seems incorrect
to not offer semantic documentation / optional validation of them.
=> Restore "regex" to the list of formats.

jsonschema-hyperschema.xml, links.json
***EDIT:*** _This PR has been rebased so that it only contains the new commits.  Originally it was posted piggybacking on #386, which has since been accepted._
-----
This addresses issue #49.
Add a keyword, "hrefRequired", that prevents a link from being
used if a variable named in that keyword's array cannot be resolved
to a value by any available mechanism.
Remove outdated language about non-object instances causing problems,
as this is addressed by "hrefPointers".
=> Control link applicability with "hrefRequired"

jsonschema-validation.xml
This addresses #305 (email) and #355 (IRIs), and also adds internationalized domain/host names as they are what the internationalized email addresses are based on.
It's a multi-commit omnibus but if any are controversial they can be split.
I also put ipv4 and ipv6 together in a section as it just reads better like that.  Alongside the "Dates and times" section introduced in PR #399, these changes result in most of the formats being grouped into sections by topic.  Only `uri-template`, `json-pointer`, and `regex` are on their own (the latter of those being introduced in PR #392).
=> Internationalized formats

jsonschema-hyperschema.xml
This addresses issue #409.  Which I just filed, so if the whole thing
gets rejected, no worries.  I can also remove the `targetMediaType`
part if that is more controversial.
"submissionEncType" is actually a media type, not an encoding,
so name it accordingly.  Rename "mediaType" to "targetMediaType"
to make it unambiguous and fit with "target" and "targetHints".
=> Name media type keywords consistently.

jsonschema-hyperschema.xml
This addresses #295.  Note that both media types referenced in the
"collection" and "item" RFC as examples of use similarly define
create-on-POST semantics.  This is the one aspect of the typical
HTTP Uniform Interface that is not identifiable purely from HTTP
method semantics, since POST, in general, can do anything.
Add a section on the IANA-registered "collection" and "item"
link relations.  Describe the common create-via-collection
pattern.  While colleciton resources described with these
link relations are not required to implement such creation
semantics, they are forbidden from implementing incompatible
behavior when used with protocols such as HTTP where the pattern
is well-established.
Note, of course, that extended link relation types may be defined
to identify collections with …
=> "collection" and "item" usage

jsonschema-hyperschema.xml, links.json
Addresses the main point of #416.  "anchor" needs to be a URI
template as the context URI will often share characteristics
of the "self" link.
***NOTE:*** Please assume this will get covered by an example
in the rewrite.  It doesn't seem worth the effort to figure one
out here.
=> "anchor" is a URI Template

jsonschema-validation.xml, links.json
We have generally included formats necessary for describing
JSON Schema vocabularies, and JSON Hyper-Schema now uses
Relative JSON Pointers.
Also use it in the links meta-schema (as a separate commit).
I did not bother to file an issue for this as it seems pretty straightforward
and in line with existing precedent.  Also, it was faster to write a PR
so even if rejected this was less work :-)
=> Add a relative-json-pointer format

jsonschema-hyperschema.xml, links.json
Addresses part of #416.  Since "href", "anchor", and "base" all share the use of "hrefPointers" and "hrefRequired", let's call them something more generic.  Note that since "hrefSchema" is NOT used with "anchor", it retains its existing name.
I am not particularly attached to the `template*` prefix. I considered `uri*`, but then would we want to change it to `iri*`?  So I went with `template*`.  But other suggestions are welcome.
=> Rename some href* keywords to template*

jsonschema-hyperschema.xml
Both of these features are extremely vague, and it seems like a good idea to provide some guidance on which headers are and are not useful for schema authors to use, and implementations to support, for each of them.
As for what it means for an implementation to support these, I'll address that more thoroughly in the rewrite, assuming this guidance is accepted.
=> Guidance on HTTP headers an "targetHints"/"headerSchema"

jsonschema-hyperschema.xml
While reworking the spec for overall flow, it became apparent
that a valuable use of "headerSchema" is to advertise content
negotiation options.  However, as currently worded, this usage
is forbidden.
Change the usage to allow this without being too burdensome
on implementations.
The rewrite will provide greater clarity on the general
implementation requirements of "targetHints" and "headerSchema",
so please do not worry too much about that for now.
=> Allow "headerSchema" for content negotiation

hyper-schema.json
It was the string "false" instead of the literal false
Addresses part of #430
=> Fix readOnly default in draft-06 meta-schema

hyper-schema.json
Addresses issue #439 
While we hope no one is still using draft-03, there's no point in publishing a meta-schema that won't even parse.
=> Fix typo syntax error.

jsonschema-hyperschema.xml, jsonschema-validation.xml
This is a bit more groundwork for the rewrite, and is relevant
to issue #423.
***NOTE:** This has been updated from its original approach to move the concept into the validation specification!*
The commits have been broken up with individual messages into useful chunks:
1. [Just move the metadata section](https://github.com/json-schema-org/json-schema-spec/pull/424/commits/dd0b873a0227e5a7a5bafbe35ae3302fa5c6ba8a)
1. [Split out and re-word "definitions"](https://github.com/json-schema-org/json-schema-spec/pull/424/commits/4f9e4e3ccdd110e054899592ff88f40de56c77b9)
1. [Generalize and move applicability from hyper-schema to validation/annotation](https://github.com/json-schema-org/json-schema-spec/pull/424/commits/c55678a7e8845ba7eb9ee334d56bc1dbaeb7c376)
1. [Group annotation keywords & …
=> Define "applicability" and "attachment"

jsonschema-hyperschema.xml
_NOTE:  This is a chunk of work that I have done as part of the rewrite.  This probably isn't quite the right way to specify it, but seems like the best way to get some feedback on the approach and changes before putting a lot of work into new prose.  Please assume that perfect examples are present wherever you want them to be :-)  I have not yet consolidated the examples into a more focused set so they're not included in this PR._
_This is one of the two most complex things an implementation must do in order to implement hyper-schema (the other thing being finding all applicable schemas per #424)._
------
This consolidates all of the URI Template resolution sections into
one section.  The new section is at the top level, as it applies
to both LDO keywords ("href", "anchor", and all of …
=> URI Template resolution as pseudocode

jsonschema-validation.xml
It is focused on the subschema form, not the string array form.
This addresses #442.
=> Clarify dependencies deprecation

jsonschema-validation.xml
This is for passwords and other senstive or write-only fields.
This addresses #249.
=> Add a "writeOnly" (formerly "secret") annotation

jsonschema-core.xml
***NOTE: This PR is [best viewed with whitespace diff off](https://github.com/json-schema-org/json-schema-spec/pull/405/files?w=1) due to indentation level changes***
This just adds the general description and the starting point for
the IANA registration.  It does not cover linking instances
to schemas in detail, which will be handled in a separate commit.
My goal for this step is just to get the media type information in the spec.
At some point, it will probably be good to consider reorganizing the information
to make it easier to find all necessary information for each media type separately.
Addresses part of #351
=> Describe application/schema-instance+json

jsonschema-core.xml
This change removes "profile", since as noted in issue #222 the
usage is not correct.  It replaces it with "schema", with the
minimal possible change.
We may wish to also remove the "describedby" link relation and
instead mandate using "schema", or a similarly named
extension relation, and allow downloading schemas based on the
parameter.  That is outside of the scope of this change.
This also continues to address #351 `application/schema-instance+json`
=> Minimal change from "profile" to "schema"

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
***NOTE:*** _No implementation requirements are changed by this PR!_
This reworks the "General validation considerations" section into
an overview that incorporates the applicability concept that was
recently added to the annotation section.  Some of the content
from that section was removed as it became duplicate content
with the new Overview.
The new Overview also talks about assertions, which is a word
used in the existing Abstract and Introduction sections.  It
helps by providing a name for the non-annotation keyword behavior,
other than "validation" which is used for the complete
specification.
The very awkward "Validation of primitive types and child values"
is covered much more clearly when written in terms of applicability
vs assertions.  These concepts map naturally to the …
=> New overview based on applicability and assertions

relative-json-pointer.xml
This addresses the source of a moderately absurd grammatical argument that @epoberezkin and I had in #115.  I took @epoberezkin interpretation and made it explicit in the specification language and gave it a section to clarify it.  Writing the hyper-schema spec with Relative JSON Pointer, it seemed more useful to be able to indicate each syntax separately.  So while I did not originally read it this way, I think @epoberezkin interpretation is the more helpful one.
Also fix a typo and add a change log.
=> Relative JSON Pointer does not include JSON Pointer, but fits with it separately

jsonschema-hyperschema.xml
There are some things that are not addressed here, and most
importantly this highlights the problems that I wrote about
in issue #421.  Hopefully they are more clear when laid out
like this and noted in CREFs.
I feel like it is a prerequisite of a hypermedia format that
claims to be feature-complete to be able to recognize
self-describing collections and make use of them without having
specific knowledge of the data type of their contents.
=> Add most of a collection example.

jsonschema-hyperschema.xml
This mostly involves explaining that hyper-schema is not a system
for executing requests and processing response.  It informs a
user agent how to construct various requests, and is used to
interpret whatever response (expected, error, whatever) is returned.
Also define "operation" up front as I keep forgetting where it's defined
and not being sure whether it was defined recently enough in the spec
for a reader to have noticed and remembered.
This is groundwork for better advice on HTTP, and is intended to provide
context around how hyper-schema systems should work with requests
and responses that is non-HTTP-specific.  The HTTP section will then
apply HTTP methods, headers, etc. to this conceptual framework
to illustrate how HTTP should be used with hyper-schema LDOs.
=> Add request/response implementation requirements

jsonschema-hyperschema.xml
...and a few other minor wording improvements around HTTP usage.
@vasilakisfil I mostly added this in reaction to your comments about reactive negotiation in your talk.  I'm not sure this is a great explanation of what I'm trying to convey, but it is a starting point at least.
=> Guidance on content negotiation

jsonschema-core.xml, jsonschema-hyperschema.xml
The update to RFC 5988 has been published as RFC 8288.
=> Replace RFC 5988[bis] with RFC 8288

jsonschema-core.xml
This addresses #221.
JSON Schema does not care about unicode characters, only the
data model.  Vocabularies SHOULD account for this by working
with data model strings instead of the original unicode
representation of numbers.
For example, define a value for the "format" validation keyword
that indicates that a string should be interpreted as a fixed-point
decimal if you wish to retain precision information in your data.
=> Clarify data model vs unicode characters

jsonschema-hyperschema.xml
***NOTE:* This is not the same tree example as before the rewrite**
It also shows why "rev" is not necessary (it is deprecated in
other link specifications, so it is omitted here), and how
to use both absolute and relative JSON Pointers in
"templatePointers".
Also fix typos and margins and stuff.
=> Example using "anchor", "base", "templatePointers"

jsonschema-core.xml, jsonschema-hyperschema.xml
Clarify what the `hrefSchema` examples mean with `targetUri`.
Use awwright's generic user agent defintion in hyper-schema.
Because it's much better than what I had there :-) 
Incorporate awwright's suggestions on CREF #1 in the core spec.
Better explanation of the concerns around and possible future
direction of `$schema` usage in the core spec.
Also add an XML comment to remind us of the most notable `$schema`
concern, so we can skip the whole thing where we forget about it
and then argue about it until we work it out again.  Which of course has 
never happened...
=> Improve wording with feedback from awwright

jsonschema-hyperschema.xml
The double space after period is from RFC 7322 (style guide for RFCs).
That CREF that I'm removing was a note-to-self thing and was not intended to be retained.
=> Fix trivial typos, remove leftover cref

jsonschema-hyperschema.xml
This pulls the pagination stuff out into a follow-up example.  There is also a commit that just changes "items" to "elements" if we decide we don't like the split.
This is in response to feedback from @dlax and @philsturgeon on the existing example.
=> Split collections example (and rename items to elements)

jsonschema-hyperschema.xml
This is an attempt to introduce concepts in a better order
and generally improve the flow.  Examples relevant to this section
will be submitted separately once decisions are made as to where
they should go.
This hopefully addresses #469.
=> Rework '"targetSchema" and HTTP'

jsonschema-hyperschema.xml
While reading this section, I felt that the example came too late after
a lot of explanation on it. So moving it up just after its introduction
paragraph.
=> Move up the JSON Hyper Schema in "mailto:" example

schema.json
"examples" is described in the draft-06 spec, but is not defined in the meta-schema.
=> Add "examples" to the draft-06 meta-schema

jsonschema-hyperschema.xml
This was left in the HTTP and targetSchema section, I think by
accident.  Let's give it its own section, and provide a bit
more of an introduction to the concepts involved, as well as
acknowledging some awkwardness in handling responses.
Addresses the remaining part of #469.
=> Give HTTP POST discussion its own section.

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
A few trivial changes.  Mostly title style changes based on [RFC 7322 RFC Style Guide](https://tools.ietf.org/html/rfc7322), which was not published when the bulk of these documents were written.  See individual commits for more.
=> "client-side user agent" is wrong, plus various formatting fixes

jsonschema-hyperschema.xml
Addresses #478.
The first commit is a few trivial typo fixes outside of the collection example.
It's best not to review the 2nd commit directly given the extent of the reworking.
Just build it and read it as an entire new example.  It was not reworked in anything
remotely resembling discrete steps, and I wouldn't even know where to start to split it.
@dlax note that several of the output URIs in the main example were flat-out wrong.
As we saw with the older tree example before the big rewrite, if you can't understand
an example it's quite likely not just badly organized but wrong.  I'll have to remember
to consider that more closely.  This is part of the problem of a spec with no implementation;
I can't just test it out.
Anyway, here are the main changes:
* Restate the item resource, …
=> Rework collection example for clarity

jsonschema-core.xml
This should clear up terms which were being used without proper definitions, and explain the rationale for vocabularies more clearly.
Addresses #480.
=> Define "vocabularies" and other related terms.

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
@handrews You earlier comment about Vim's spellcheck for XML files bugged me and I found that `:syntax spell toplevel` (in addition to `:set spell`) makes spellchecking work on tag's text.
=> Typo fixes

jsonschema-hyperschema.xml, jsonschema-validation.xml
This is probably about as much as we'll do for draft-07.  We'll keep working on the security sections as the drafts progress, but this is at least as good as it has been for the last few drafts.
Addresses #456 plus various things not filed as issues.
Commit log:
```
|     Security considerations for "content*"
|     
|     a.k.a. don't take executable content types from strangers
|  
* commit 58c6b96cb13d5a593209154cc854067c3bf0e954
| Author: Henry Andrews <henry@cloudflare.com>
| Date:   Tue Nov 14 12:44:59 2017 -0800
| 
|     Add a bit more about target attribute authority
|     
|     While "targetSchema" is technically never required to process
|     a response, as the response should indicate its own schema,
|     other target attributes in the LDO, such as the submission schema,
| …
```
=> Numerous improvements to security considerations

schema.json
Addresses #486 (sorry, @epoberezkin, I'm trying to nail down
as much as possible by end of day tomorrow/Friday, so can't
wait for your PR :-)
Let's emphasize the clarity of the boolean schemas as that is
why they were added.
Note that the default values of "definitions", "properties",
and "patternProperties" is an actual empty object, not an
empty schema, so those stay as they were.
We were using an explicit empty schema to emphasize/document
that a keyword accepts any possible value in several places,
but were not using it in a few others such as "items" within
the "enum" schema.  Consistently make it explicit.
There were no empty object subschemas in the other meta-schemas.
I used ajv to validate the schema against itself, which worked fine.
=> Use boolean true instead of {} where possible

jsonschema-hyperschema.xml, jsonschema-validation.xml
Addresses #471.  Note that no changes were needed in the core spec, and the commented-out RFC reference that was left in hyper-schema will be addressed by the next PR.
I left the HTTP RFCs (including PATCH) as informative because there is guidance on how they are used but I don't think anything rises to the level of a testable requirement, even an optional one.  Implementations, for instance, are not obligated to look for "accept-patch" in "targetHints", and if they do, the general directive that the meta-data is treated according to whatever protocol is in use is sufficient.  Additional information is present only to reduce confusion.
The one way in which this might not be correct is the requirement that API implementors MUST NOT define POST semantics for a collection other than …
=> Fix normative vs informative references

jsonschema-hyperschema.xml
Avoid "client" on its own where possible.  Use "client application",
"user agent", and "client input" as defined in the Terminology
section to clarify roles and responsibilities.
Reviewers, please check and see if this actually improves clarity.
It's also possible that I "corrected" one or two things in the wrong direction,
so check the context please.
=> Normalize "client" terminology

jsonschema-hyperschema.xml
This should be enough to give a feel for the basics without
needing a detailed explanation or taking up too much space
during the introductory sections.
Addresses #473.
=> Add minimal example to the hyper-schema Overview

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
Add the more philosophical changes to the change logs, plus
adding a few other missing bits and fixing an outdated line.
=> Final changelog updates

jsonschema-hyperschema.xml
For some reason the reference to the Atom RFC, where "self" was
originally defined, was commented out.  Restore the reference
and cite it.
The text for "self" was confusing in that it was unclear which
parts applied in general and which parts applied to only "self"
links for the entire instance document.  Rearrange some sentences
to make that more clear.
Also partially addresses issue #485 by improving CREF text about
the "self" security concerns.
=> xref for "self" rel type, improve the wording for usage guidance, security concerns

jsonschema-hyperschema.xml, jsonschema-validation.xml
Also, I was using <eref/> wrong in the hyper-schema, and for
some reason we weren't using it at all in validation.  Made
all of that consistent now.
=> Finalize meta-schema URIs for draft-07

hyper-schema-output.json, hyper-schema.json, links.json, schema.json
Prepare for publication of official meta-schemas for draft-07.
This `draft-07` branch will be rebased as needed for any further changes before publication, and then brought over to the upstream repository for ongoing use for any meta-schema bug fixes.  Which we've needed to do for drafts 3, 4, and 6.  Repeatedly :-P
=> draft-07 meta-schemas, no longer -wip

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
NOTE: This is a mechanical change in prep for submitting to the IETF,
so as long as the build passes I will go ahead and merge.
* These are being submitted as a set, so update all to reference
the newly submitted versions
* A. Wright gets first billing on Core and Validation
* H. Andrews gets first billing on Hyper-Schema
* G. Luff gets first billing on Relative JSON Pointers
I'm not sure how I ended up listed first on validation, but it
was not intentional.
=> Update cross-references and authors/conributors

jsonschema-hyperschema.xml
What is it about publishing/releasing something that makes
errors jump out of text that you (and others) went over so
many times during final review?
* "base" URIs need to end in "/" for the "href" values to work,
although when "base" has no path component it probably works
either way
* "-wip" got left in the example meta-schema URIs :-(
* A cref about "-wip" being a placeholder got left in, although
not anywhere near the examples where the "-wip" was otherwise
apparent
* Tree node example lacked "$id", "$schema", and opening {
* There was no text in between the collection schema and instance
These are small but potentially quite confusing.  I plan to add an errata
list to the web site, but after some time for other obvious errors to be
spotted it might be worth publishing a purely bugfix …
=> Various hyper-schema example fixes

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
The core spec's change log seemed to have been spliced across
draft-04 and draft-00.  This dates back to draft-04.  Move the
obviously draft-04-related stuff up to that part of the changelog,
and add a line about splitting out hypermedia (analogous to the
existing line about splitting out validation).
It did not seem worthwhile to import the old changelogs from
draft-01, -02, and -03, although we can do that if necessary.
This change just fixes things that really did not make sense.
Also, in both the validation and hyper-schema specs, the oldest
draft was erroneously numbered -01 when it should be -00.
_**NOTE:** I'll probably also merge this to the draft-07 branch,
since if we do a bugfix this would be fine to include._
=> Fix several early changelog oddities

relative-json-pointer.xml
This was correct in the syntax/behavioral description, just
named incorrectly.  Outdented the ABNF to avoid warnings about
it being outdented automatically.
=> Fix positive -> non-negative in text (Relative JSON Pointer)

jsonschema-hyperschema.xml, relative-json-pointer.xml
This is just for Hyper-Schema and Relative JSON Pointer, both
of which need some bug fixing.  In particular, the hyper-schema
meta-schema link and some aspects of examples were blatantly
wrong and would not work.
***If folks think I should push all three instead, we could clarify
some wording and do that- there's been at least one wording
complaint on if/then/else, for instance.  But I don't want to
hold things up for that, or add new keywords or change behavior.***
This is against "newyear" which is against "master".  Once these
are merged to "master", I will merge "master" to "draft-07" and
tag new releases of these two specs.  The only commits on master
since the handrews-*-00 tags are:
* actual bug fixes to hyperschema (already on draft-07 and master)
* fixing the munged old …
=> Prep for handrews-*-01 (Hyper-Schema and Rel JSON Pointer **ONLY**)

jsonschema-core.xml
***NOTE:* This PR is broken into several commits for easier review.  Some commits relocate large blocks of text, others rework and expand existing content.  No commits do both.  It is probably worth looking at individual commits for diffs, but building the branch locally to look at the complete flow of the reworked section to get a feel for how it reads as a whole.*
This addresses #545.
The "Internal References" concept and explanation was confusing, as noted in #545.  The "External References" was really just a discussion of schema identification uniqueness and whether or not you can load remote schemas.
It felt odd to me to introduce `$ref` before `$id`, as you need to understand identifying schemas before you can reference them by identifiers.  So I re-ordered that.
In the `$id` …
=> Remove internal/external reference terminology, expand use cases and examples

links.json
I have no idea why this was like this, but fortunately they
both did the same thing.  One was needlessly complex.
This will get updated in place as the published draft-07
meta-schema as it's less confusing and functionally identical.
=> Remove duplicate hrefSchema from meta-schema

jsonschema-validation.xml
Also other minor wording clarifications for if/then/else such as
standardizing the "regardless of the validation outcome against
the subschema" language.  That language is important as it
clarifies that subschema validation can fail (causing annotations
to be dropped) without causing the containing schema to fail.
=> Fix missing "if present" for "else"

jsonschema-core.xml, jsonschema-validation.xml
This makes the draft numbering change and adds the change log for doing a clarification / bugfix draft of core and validation.  The changes include:
* Clarifications on `$id` and `$ref` (previously merged: #550 and #551)
* Clarifications/bugfix on `if`/`then`/`else` (#554)
* Minor list formatting improvements (first commit of this PR)
* Updates to CREF for proposals regarding `dependencies` (second commit of this PR)
The usefulness of the `$id`/`$ref` clarifications in core should be readily apparent.
For validation, the `if` change seems worth publishing because a.) I've received two separate complaints/questions about it, and b.) the validation spec would otherwise be the only one still on handrews-00 so we might as well publish an update even though it's very small.  It does address a …
=> handrews-*-01 bugfix for core & validation

jsonschema-core.xml, jsonschema-validation.xml
This does not change the intended behavior, but generalizes some
points presented as exceptions (e.g. why annotations under "not"
are never used), and calls annotations out as a first-class use
case in the core specification.
This also improves the if/then/else change log (because I had not
yet added the change log in the commit for if/then/else revisions,
but it got held up past the change log commit).
=> Emphasize and clarify annotations

hyper-schema-output.json, hyper-schema.json, jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml, links.json, schema.json
This updates the various numberings to avoid confusion between
the work-in-progress drafts and the published draft-07 and
draft-handrews-*-01 documents.
Having examples using new keywords but referencing draft-07
is confusing, as is having meta-schemas identified as draft-07
with keywords that are not part of draft-07.  Similarly, having
a set of draft-handrews-*-01 documents that are buildable
that do not match the published ones is confusing.
Last time I did some "-wip" suffixes but I'm not sure how
clear this was to anyone else, and the main result was that
I accidentally left about half of them in at publication :-(
This seems more straightforward.
=> Initial update for draft-08 / handrews-*-02

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml, relative-json-pointer.xml
=> Add minContains and maxContains

hyper-schema-output.json, hyper-schema.json, jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml, links.json, schema.json
Includes updates of the meta-schemas and examples to match.
Addresses #512 
_**NOTE:** There are multiple commits to make this easy, as it's all very simple and mostly mechanical, but if you look at it all together it looks big.  The commits in order:_
* _actually move/rename_
* _add the appendix to the validation spec_
* _add to meta-schemas_
* _use in meta-schemas_
* _update examples_
=> Move "definitions" to core as "$defs", start appendix on moved/renamed keywords

jsonschema-core.xml, jsonschema-validation.xml
"dependencies", with the schema behavior, moves to the validation
spec with the other applicators.  "requiredDependencies", with
the property array behavior, stays in validation as an assertion
alongside "required"
=> Split "requiredDependencies" out of "dependencies"

jsonschema-hyperschema.xml
`someone@exapmle.com` -> `someone@example.com`, rest of the example doesn't seem to have the same typo.
=> Email payload example typo fix

jsonschema-hyperschema.xml
One commit for each:
* Fix typo "attachmentUri" -> "attachmentPointer" #552 
* Fix example querystring (ampersand vs comma; correct offsets) #548
=> Minor hyper-schema fixes

relative-json-pointer.xml
Also administrative updates (in a separate commit) for draft numbering and changing my affiliation for the editor credit.
=> Relative JSON Pointer update for new JSON RFC

jsonschema-core.xml, jsonschema-validation.xml
Move the main text into core, and just reference it from validation.
This somehow got left off the PR back when the applicators moved to core, and I only just now noticed.  Core now includes keywords that use regexes.
=> Update regex concerns for subschema application

jsonschema-core.xml
_**NOTE:** The second commit in this PR indents for a new section without changing the text, so it's best to look at each commit separately._
This is groundwork for more of the vocabulary and annotation
collection process work.
Move the general description of applicators from the applicator
vocabulary to a section alongside the Assertion and Annotation
sections.  Rework the text a bit, and also clarify an aspect
of annotation collection related to applicators.
Group the Annotation, Assertion, and Application sections
as Keyword Behaviors.
Arguably, this has overgrown the "Overview" section, but since
the "Vocabulary" part of the overview is also about to be
expanded, let's wait until then to figure out how to refactor it.
=> Create an Applicators section, group into a Keyword Behaviors section

jsonschema-core.xml
_The base of this PR is PR #595, not the current master_
This is the critical conceptual change that lets us implement #556 `unevaluatedProperties` and #557 `unevaluatedItems`.
There are three commits- two significant one and one mechanical one removing outdated text.  These are grouped together to ensure that a real-world use of the new concepts, with the familiar `additionalProperties` and `additionalItems` keywords, is included with the more abstract changes.
The [first commit](https://github.com/json-schema-org/json-schema-spec/commit/b0c208b378e3f540e215dfe19bf152cf7ecf1062) describes the newly allowed behavior and its implications for all types of keywords.  In particular, this required working out how default keyword behavior works with respect to annotations.
The [second …
=> Keywords can depend on subschema or adjacent keyword annotation results

jsonschema-core.xml
This does not change any text at all.  The initial part of
the Keyword Behaviors section is too long.  Put some of the
existing paragraphs into subsections on keyword interactions,
and on default behaviors, which are very distinct topics.
This left the paragraph on extension keywords orphaned, so
I moved it up.  The topic of extension keywords will be
revisited in detail with the vocabulary changes, so it's best
not to worry too much about exactly where this paragraph goes
right now.
As this is purely a formatting / clarity change, it will not sit
up for the full 2 weeks (per longstanding policy).
=> Trivial: Split Keyword Behaviors in to better subsections

jsonschema-hyperschema.xml
* add missing semi-colons
* quote all parameter's value (per consistency)
* fix "anchor" by quoting value instead of enclosing between <>
Fixes #623
=> Fix Link header examples in hyper-schema

hyper-schema.json, schema.json
Which has apparently been wrong the whole time.
Also, we apparently forget `contains`.
Also fix minor formatting inconsistencies.
=> DRAFT-06 Fix propertyNames and contains meta-schema

jsonschema-validation.xml
Addresses #594 
[RFC 4648](https://tools.ietf.org/html/rfc4648) is a more modern standard for encodings, and addresses
ambiguities and application-specific limits of the "base64"
encoding from [RFC 2045](https://tools.ietf.org/html/rfc2045).  It also adds several commonly used
variations, such as "base64url", that are relevant to modern systems.
RFC 2045 values are still allowed, although for "base64", RFC 4648
now takes precedence.
=> Allow RFC 4648 encodings for "contentEncoding"

jsonschema-core.xml
"$comment" is not an annotation.  Now that we have the concept of
keyword classifications, this makes the distinction between
"description" (which is an annotation) and "$comment" (which is
not) more clear.
=> Clarify $comment and annotations

jsonschema-core.xml
For several upcoming features, we need better language to
talk about the schemas on either side of a "$ref" or similar
linking keyword.
In particular, annotation collection (#530) interacts with references,
and calling referenced schemas "subschemas" is confusing and
technically inaccurate.
=> Explain referenced/referring schemas

hyper-schema.json, schema.json
But leave the other minor formatting improvements
=> [draft-07] Undo incorrect "propertyNames" change

links.json, schema.json
With default values now having implication for both assertions
and annotation collection (see PR #600 for this), it no longer
makes sense to have a default value for subschemas.
Keywords such as `additionalProperties` now collect annotation
information based on the instance properties to which thier
subschema(s) are applied.  This means that a subschema of true
will cause a property to appear in the annotation, while an
absent subschema will not.  Therefore, a default of true does
not match the annotation collection behavior and is not accurate.
Additionally, as written this has always been problematic, as
it claims a default true value for `not`, which would in fact
cause all schemas without `not` to fail.
-------
However, the Hyper-Schema LDO schema keywords do have
reasonable defaults: …
=> Fix default usage in meta-schemas

jsonschema-core.xml
$ref no longer effects other properties in the same object.
Updated phrasing to align with current wording.
Resolves #514 and resolve #523
Opened in favour of https://github.com/json-schema-org/json-schema-spec/pull/585
=> Ref is delegation - try 3

jsonschema-core.xml
***NOTE:*** _This PR uses language added in PR #609, which was recently merged._
This covers the basics of annotation collection (#530), and its interaction
with assertions and applicators.  It does not get into the exact
output structure for annotation results, which is intentional.
The goal is to establish the process, and then nail down the
format once the process is solid.
=> Initial description of annotation collection

jsonschema-hyperschema.xml, links.json
Addresses #350 
This follows the precedent of "type" by allowing "rel" to be
either a single string, or an array of strings.
Also paging @mokkabonna
=> Allow multiple values for "rel"

hyper-schema.json, jsonschema-core.xml, jsonschema-validation.xml, schema.json
Upon further discussion in https://github.com/json-schema-org/json-schema-spec/issues/591#issuecomment-398596184, the grammatical
approach that is most intuitive was deemed to be that the
string array or schema's usage is dependent upon the presence
or absence of the instance property.
In at least some anecdotal reports, the nature and
direction of the "dependencies" concept proved confusing.
Others found it intuitive.  The revised wording aims
to explicitly tie the dependency direction to the
naming convention.
In addition, while there was some debate over the most
migration-friendly strategy, the decision is to leave
the old form of "dependencies" available as an extension,
and for at least one draft use the meta-schema to avoid
its redefinition.  Therefore both keywords resulting
from …
=> Name the split "dependencies" to "dependent*"

jsonschema-hyperschema.xml
Since the URI in the `GET` is `https://api.example.com`, presumably the text was supposed to be referring to that URI as well.
=> Fix entry point URI in example description

jsonschema-hyperschema.xml
Prepopulated title comes from the instance's title property, which didn't include the word "really".
=> Fix prepopulated title in example

.travis.yml
From version 2.10, option --basename changed its semantics and is now
expected to be a directory, which does not fit our current usage.
Alternatively, we could drop this option altogether (and thus avoid
version pinning) since I'm not sure what this is for.
=> Require xml2rfc < 2.10 in travis build

jsonschema-core.xml
***NOTE:** I'm breaking this up into three parts to keep each one a bit more focused.  The first two are on the core spec file, but do not overlap in line numbers or even sections.  There are some references between them but figuring them out should be straightforward.  I'm not entirely happy with this write up (particularly the 2nd part), but I have been struggling with this for at least two months and just need to get something out there to unblock progress.   Hopefully we can edit this into something workable.*
This is some groundwork for #558 $recursiveRef/$recursiveAnchor,
formalizing lexical and dynamic notions of scope in ways that
should be quite intuitive given how the concepts are used in
a wide variety of programming languages.
=> $recursiveRef part 1 of 3: Dynamic vs Lexical scope

jsonschema-core.xml
Address #556 and #557.
The only slightly unusual thing here is that while `additionalItems` only takes effect when `items` is present, due to the more dynamic nature of `unevaluatedItems`, I decided that it could take place whether `items` is present anywhere or not.
I believe the restriction on `additionalItems` is to avoid an ambiguity where you can use either `items` or `additionalItems` to perform the same assertion.  Requiring `additionalItems` to be ignored in the absence of `items` makes the single-schema use of `items` unambiguously the only way to validated every item in an array.
For `unevaluatedItems`, it seems more correct for it to apply even when no array elements have had a schema evaluated against them, rather than requiring that somewhere in the depths of subschemas there …
=> Add "unevaluatedProperties" and "unevaluatedItems"

jsonschema-core.xml
***NOTE:** I'm breaking this up into three parts to keep each one a bit more focused. The first two are on the core spec file, but do not overlap in line numbers or even sections. There are some references between them but figuring them out should be straightforward. I'm not entirely happy with this write up (particularly the 2nd part), but I have been struggling with this for at least two months and just need to get something out there to unblock progress. Hopefully we can edit this into something workable.*
Addresses #558 
These keywords allow for recursive extension of schemas,
in the way needed by meta-schemas.  This is not Object-Oriented
extension, rather it is a shortcut for the kind of "allOf"
combination that is already allowed, but without the need to
redeclare all recursive …
=> $recursiveRef part 2 of 3: $recursiveRef and $recursiveAnchor

hyper-schema.json, links.json, schema.json
hyper-schema is a lot simpler now.
=> $recursiveRef part 3 of 3: Update meta-schemas

jsonschema-hyperschema.xml
Addresses the immediate concerns of #581 (paging @davidarnold, my apologies for taking so long to get around to this).
Based on feedback that the current wording, in the context of
all the discussion of POST-to-create-via-collection, can give
the mistaken impression that PUT cannot create.
While we are not responsible for explaining all HTTP semantics,
we can make a bit of an effort here to ensure that we do not
confuse more people.
=> Acknowledge that PUT can create

jsonschema-validation.xml
Addresses #669 (paging @gcallaghan)
Also clean up some of the wording for the other content keywords.
Include a JWT example.
=> Add "contentSchema"

schema.json
This supports https://github.com/json-schema-org/json-schema-spec/pull/653, https://github.com/json-schema-org/json-schema-spec/pull/654, and https://github.com/json-schema-org/json-schema-spec/pull/655.
=> Added '$recursive*' to the meta-schema

jsonschema-core.xml
Nudge readers a bit more clearly to consider things like 'file://'
URLs and not just network URLs when constructing a location-based
base URI.  Also refer directly to the rules for application-specific
default URIs.
This was motivated by https://github.com/Julian/jsonschema/issues/343#issuecomment-441527562 over at @Julian 's implementation repo.  And I'm pretty sure I have seen similar confusion from users, or unexpected/unexplained behaviors from implementations elsewhere.
Referring to RFC 3986 section 5.1.4 also points people to the "if you send a thing you are responsible for it having a base URI" guidance.
=> More guidance on initial base URI

jsonschema-core.xml
Addresses #649 
application/schema+json MAY use the same mechanism as
application/schema-instance+json to identify its meta-schema,
although with application/schema+json, the "$schema" value
within the document is considered the canonical meta-schema.
=> Allow "schema" media type parameter for schemas

applicator.json, core.json, jsonschema-core.xml, schema.json
_It is recommended that the commits in this PR be reviewed one at a time, to avoid formatting changes making things more complicated than they are.  See also their individual commit messages._
Addresses #561, #564, #567 
I expect the wording here to have to go through some revision, but as is often the case I decided I just needed to post *something* to get the conversation started.
Key points:
* When declaring the use of a vocabulary, you can indicate whether it is required or not, but that is all
* ~For now, I'd rather not mandate any sort of vocabulary description file.  As we get feedback, we will no doubt learn what is best put there.  On the other hand, if implementation maintainers would like to hook specific keyword detection into their extension mechanism, I could reconsider and …
=> "$vocabulary" and basic vocabulary support.

jsonschema-core.xml
Resolves #607 
This explains how to use HTTP content negotiation to request
representations that conform to multiple schemas, or conform
to at least one schema out of several.
=> Explain schema media type param and Accept

jsonschema-validation.xml
=> Add a "duration" format.

jsonschema-validation.xml
RFC 1123 modifies the syntax to allow a leading digit, which is
present in modern practice.
=> Update hostname RFC reference

jsonschema-validation.xml
It would seem to me that `const` is the same as a single-valued `enum`.  If that's correct, then that should be noted.  If it's not, then the difference should also be noted.
=> Clarifying "const" usage.

jsonschema-validation.xml
=> Add "uuid" format

jsonschema-core.xml, jsonschema-validation.xml
Fixes #687 (in the sense of "it's clear what you are and are not required to implement", not in the sense of "solves the underlying applicator keyword recognition issue", which will be part of the draft after this as it is quite involved").
The most common situation here, which are basically alternate
names for "definitions" or "$defs", will generally work, but
this makes clear that there is no obligation to attempt to
guarantee the proper behavior in such situations.
We might want to narrow this behavior down in the future,
but for now this at least clearly removes any possible burdensome
and totally impractical inferencing requirements.
=> Note undefined behavior with unknown $ref targets

jsonschema-validation.xml, meta/meta-data.json
There is often talk about getting OpenAPI in line with JSON Schema, but this is one instance where JSON Schema can be brought in line with OpenAPI, with a new`"deprecated"` keyword.
Just a simple true/false (default false) for this keyword, and it means the thing might be going away sometime. Easy.
**Justification**
There have been talks of all sorts of complex forms of deprecation, including deprecatedSince and deprecateVersion and deprecate*d*Version over on OpenAPI, and this lead to all sorts of confusion for me in what JSON Schema should do.
I have thought through this on and off for months, and it's become clear to me that since JSON Schema currently has no concept of versions or dates or any sort of timeline, there is no reason to start trying to add a whole new dimension just for a …
=> Fix #74: add "deprecated" keyword

meta/validation.json
Issue: https://github.com/json-schema-org/json-schema-spec/issues/717
enum no longer requires minimum number of items or unique items, in accordance with the spec.
=> Fix enum definition according to spec.

jsonschema-hyperschema.xml, jsonschema-validation.xml
Also a reference within the validation spec was accidentally
done as a cross-ref to core, so fixed that as well.
Fixes #721
=> Fix cross-references

jsonschema-core.xml
In the first version, I mention that the error message property itself is not a requirement, but in the "output unit" requirements I specify that an error message is required, soooo.....
=> fixed note about error message wording

jsonschema-core.xml
Include another reference to RFC 3986 to try and make things clearer for schema documents that define no explicit base URI.
Align phrasing.
Fixes #745
=> Try to make Base URI resolution for a document clearer

jsonschema-core.xml
I think this dramatically improves the flow of the document.  There is almost certainly more to do, but just having a concise overview and going from brief descriptions to detailed descriptions is a vast improvement.
The "Keyword Behavior" section is moved, completely unchanged,
to immediately after the "General Considerations", where
it makes quite a bit more sense.  The "General Considerations"
section gives a brief description of the keyword types,
which makes a lot more sense before the detailed description
rather than after it.
The old "Schema Vocabularies" section has mostly been deleted,
as it took up a lot of space without adding much.  Given that
the validation spec now contains four or five vocabularies,
enumerating all of them plus hyper-schema (which is highly
unlikely to …
=> Make a real, appropriately short, Overview section

hyper-schema.json, jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml, links.json, meta/applicator.json, meta/content.json, meta/core.json, meta/format.json, meta/hyper-schema.json, meta/meta-data.json, meta/validation.json, output/hyper-schema.json, output/schema.json, output/verbose-example.json, relative-json-pointer.xml, schema.json
The first commit changes all of the meta-schema and vocabulary dates to `2019-08`.  I'm pretty sure we're not publishing this within the next week, and if we do we can always reset them to 2019-07.  I'm working on things as quickly as I can.
It also makes everything `https://` including examples.  I could be convinced to change the examples back, but I think we'd already agreed to to HTTPS but just hadn't changed it consistently (it was really random).
The next commit fixes a typo in a meta-schema URI.
The third commit removes Riverbed from my credit and changes my email since I no longer work there.
The final commit removes G. Luff from the co-author list of the validation spec because he appeared to have been added by error in draft-wright-...-00 (copy-paste from hyper-schema, I think). …
=> Fixes to dates, author credits, HTTPS

jsonschema-validation.xml
Addresses the 'content*' part of #646.
They no longer optionally funciton as validation assertions
in order to ensure consistent and interoperable behavior.
=> Make the "content*" keywords annotations only

jsonschema-core.xml, jsonschema-validation.xml
Fixes #768.  No release notes because the part about "contains"
not collecting annotations was never in the release notes, and
it wasn't in the previous draft either.
In particular, "contains" collects annotations.  I'm not sure
where the exception came from, as it was not present in the
previous draft (to the extent that that draft mentioned
annotations).
The CREF actually did talk about annotation collection so
apparently this was a bit of a muddled mess anyway.
This makes "contains" behave like all other applicators,
producing both assertion and annotation results.
=> Clarify annotation collection with applicators

jsonschema-core.xml
Attempt to make this more understandable by removing
some duplication, putting things in the right order,
and explaning certain things more clearly.  Hopefully.
_It might be easier to just download and build this to review._
=> Restructure vocabulary-related sections

hyper-schema.json, jsonschema-validation.xml, schema.json
Fixes #732, fixes #759, addresses the `format` part of #646.
The `content*` of #646 will be done in a separate PR.
Use the true vs false values of vocabulary declaration to
indicate whether a schema author requires assertion behavior
(such as because a keyword such as "oneOf" depends on such
validation functioning correctly).
Use a false value in the standard core+validation vocabulary,
reflecting the historical lack of requirement for this
keyword to be implemented.
Define annotation behavior when the vocabulary is declared with
false, to facilitate the recommended best practice of performing
semantic validation in your application.  While not the typical
false vocabulary behavior, this seems like the best way to
reframe the historically unpredictable behavior.
=> Specify "format" requirements in vocabulary terms

jsonschema-core.xml
***NOTE:** This does not change any text, it only moves three complete sections to new locations.*
Several sections related to fundamental keyword behavior had
ended up scattered around the document.
The bit about scopes makes more sense near the top of the keyword
behaviors section, as it is really talking about how keywords
interact with the concept of scopes.  It probably does not need
to be in the basic description of schema documents, where it was.
The section on referenced and referencing keywords is closely
associated with applicators, so it becomes a subsection of that.
Finally, the entire section on how to collect annotations gets
moved under the annotations section in keyword behaviors.
This consolidates all generic keyword behavior descriptions
into section 7. Keyword …
=> Consolidate keyword behavior sections

jsonschema-core.xml
Based on @awwright's suggesetion in the slack channel.
=> Example of assertion independence per awwright

jsonschema-core.xml
Fixes #774 .  Note that I found a better reference, [section 15.10.1](https://www.ecma-international.org/ecma-262/5.1/#sec-15.10.1), than I mentioned in the quote in the issue.
This does not change any behavior, it just ensures that no one thinks we meant the RegExp literal syntax.  Something resembling a RegExp grammar is given in three different places (the RegExp literal section, the actual normative pattern definition in 15.10.1, and an informative definition in A.7), so it's a little confusing to the casual spec reader without a section reference.
=> Give ECMA 262 reference section for RegExp dialect.

jsonschema-core.xml
_**IMPORTANT:** There are two commits here.  The first commit **only** moves the core vocabulary section out a level, nesting the various core keyword definition sections under it.  The second commit has several minor changes to improve flow in the new layout.  It will be a lot easier if you look a the diffs separately for each commit- the change is quite minor when examined that way._
Really, Core should be like any other vocabulary, grouped into a single section.
A few minor clarifications are added, including a RECOMMENDATION
against using "$" as the first character of extension keywords.
The paragraph about bug-fix meta-schema and vocabulary URIs seemed
out of place, and worth calling out more clearly, so it became
its own section.
=> Wrap the entire core vocabulary inside the core vocab section.

jsonschema-core.xml
Two improvements extracted from the previous vocab example PR by Greg:
* better wording around "forthcoming drafts" (kept verbatim)
* clarification around keywords from unknown vocabularies
(loosely inspired by Greg's wording).
=> Vocab explanation improvements from gregsdennis

output/verbose-example.json
Follows on from 5b088711e78d472905ed37481d5ca055f370ba05.
=> Fix verbose example to use `$defs`

jsonschema-core.xml
This is heavily based on @gregsdennis 's work in PR #756.
Hopefully it is now more clear why I went off and updated a bunch
of other things before coming back to this.  What I found while
reviewing that PR is that the example wasn't great to begin with,
and in a few places was outright wrong.  This, understandably,
led to some of the enhancements to the example not being
quite right either.
Most notably, the old example should not have been set up
as its own meta-schema.  I can barely even figure out why
I must have done that, it makes so little sense 😕 
The example now follows the best practices from the previous
section by showing separate general purpose and single-vocabulary
meta-schemas, and discusses how they are used together.
I also switched "startDate" to "minDate" so that the …
=> Improve vocab example per gregsdennis suggestions

jsonschema-core.xml, jsonschema-validation.xml
Fixes #778 (paging @about-code).
Acknowledge that "$defs" and placeholders like it also indicate
that their values are schemas, which is relevant to whether
they can be detected as a proper "$ref" target or place where
"$id" may appear.
This ensures that similar extension keywords are understood
to have the same concerns as extension applicator keywords.
I did not add anything about `$defs` being recommended, because
now that it is covered in the same way as the applicator vocab,
it is clear that you can add more extension keywords like it.
And I think it is inherently clear that keywords in Core are recommended.
[See later comments from me about a few further changes]
=> Clarify the nature of schema placeholder keywords

jsonschema-core.xml
=> Fix $comment paragraphs

jsonschema-core.xml, jsonschema-validation.xml
Fixes #786.
Remove wording that is no longer meaningful now that we have
recommended output formats.
Also do not use meta-schema as example for relative and absolute
paths because my brain broke trying to figure out what it was doing.
Finally, a few tweaks in the output description where I felt it was 
a bit confusing- @gregsdennis let me know if these are wrong or if
you feel they're a net negative.
=> Improve guidance on annotations and output

jsonschema-core.xml
This is going to be a powerful technique for generative use
cases, which have been observed either requiring references
(as opposed to subschemas) in certain places, or implementing
various sorts of inferencing around references on their own
or in conjunction with other keywords.
For example, one OpenAPI documentation tool assumes that
in an "allOf" of several references, the first is a base
class of some sort. While this is not correct behavior
by either JSON Schema or OpenAPI, it demonstrates a feature
built by making implicit assumptions about certain references.
This section provides a recommendation for making such
behavior explicit, and also guides writers of such tools
to the concept of extension vocabularies and annotations.
=> Generative use case guidance

hyper-schema.json, jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml, links.json, meta/applicator.json, meta/content.json, meta/core.json, meta/format.json, meta/hyper-schema.json, meta/meta-data.json, meta/validation.json, output/hyper-schema.json, output/schema.json, schema.json
Trying to get things finalized...
=> Update meta-schema dates, minor changelog typo

hyper-schema.json, jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml, links.json, meta/applicator.json, meta/content.json, meta/core.json, meta/format.json, meta/hyper-schema.json, meta/meta-data.json, meta/validation.json, output/hyper-schema.json, output/schema.json, schema.json
***[EDIT:** I pushed a commit Saturday just before 1PM california time that I think simplifies things considerably- see the commit log message for details.]*
*THERE ARE THREE COMMITS (originally, and then more added)*
While this is all one coherent change, and the commits don't fully stand alone, I have organized them to make reviewing a bit easier.
* First I define a schema resource
* Then I deal with URI shadowing (#726) _somewhat obsoleted by the 4th commit_
* Then I deal with `$anchor` (#729) _and_ update the examples
* Feedback on URI shadowing and fragments in `$id`
* Update meta-schemas
* Fix more examples
* Add changelog
Fixes #729.  Fixes #726. 
This implements the recent decision to strongly discourage using fragments that cross a base URI change (e.g. an `"$id"` appearance). …
=> Split $anchor out of $id, define canonical vs shadowed URI behavior

jsonschema-core.xml
***NOTE**: The first commit is just a move, the second changes the RFC 2119 terms.  They should be examined separately.*
These sections are not normative, and moving them to an
appendix reduces the length of the sizable normative
portion of the spec.  And also improves flow, I think.
The examples within core tend to rely on understanding more
of the core keywords than have necessarily been introduced,
so they work better after the entire vocabulary has been
introduced.
Vocabulary authorship is not part of the JSON Schema specification,
so this guidance should not use RFC 2119 terms.
=>  Move core examples/best practices to appendixes

jsonschema-core.xml
So.. I know I said I was done, but... I went to add a bit about `$id` and `$anchor` being identification keywords (alongside assertions, annotations, applicators, and reserved locations), because it seemed like it might fix a conceptual gap and help folks understand what we're doing with the split, and then I realized that `$recursiveAnchor` fit into this category if we think about it as dynamically setting the base URI for resolving `$recursiveRef`.  So that's the first commit.
This led to a much more straightforward way of explaining how these keywords work, so I reworked that whole section.  I feel like with the new presentation, the elaborate justification is not required.  That's the second commit (including removing the old example).
The third commit is the new example, explained in …
=> Clarify "$recursiveAnchor" behavior in terms of base URIs

jsonschema-core.xml
fix nesting and structure of JSON example. the existing JSON is indented incorrectly, contains a closing `}` with no corresponding `{` and doesn't parse.
=> fix invalid JSON in 7.7.1.1. Distinguishing Among Multiple Values

jsonschema-core.xml
Somewhere along the line, any explicit statement of how these
keywords contribute to schema results got lost.
Put it back in, and add a CREF to ensure that people understand
the implications for keywords adjacent to "$ref".
=> Clarify the results of $ref and $recursiveRef

meta/core.json
Found this while testing when the meta-schema didn't validate its own `$id`.  If we prefer something else, that's fine, just probably test that it works first.
=> fixed regex for $id in core metaschema

relative-json-pointer.xml
hi friends,
the content I've changed here is showing up incorrectly on the web site
https://json-schema.org/draft/2019-09/relative-json-pointer.html as `non-negative-integer &lt;json-pointer&gt;`
I don't know XML too well - whether literal `<` is allowed in CDATA, or if I've just made an invalid change, but the current output is incorrect.
=> fix relative-json-pointer xml character entities used in CDATA

jsonschema-core.xml
=> `figure` should be a child of `section`, not `t`.

relative-json-pointer.xml
Looks like if you have a `t` tag with a `list` tag, you're not expected to have other tags at the same level.
I couldn't find the documentation to confirm this, but this change does seem to fix the issue.
=> Make sure xref is wrapped in `t` tag to fix #814

jsonschema-core.xml
Per the following issue: https://github.com/json-schema-org/json-schema-spec/issues/824
=> Update to 10.4 "Output Structure"

jsonschema-core.xml
=> Don't refer to JSON values as "productions".

jsonschema-core.xml
We are adding a section dealing with loading, processing,
and referencing schemas.
These sections have been moved without any changes to text or
formatting beyond adjusting the indentation to fit the new
location.
This is the first step for #849.
=> Consolidate schema loading sections

jsonschema-core.xml
Left this out of the earlier section rearranging.
This is just a move and indent, no change to the text at all.
=> Move hypermedia to loading section

jsonschema-validation.xml
Fixes #852 
We were referring to 5322 when we really wanted 5321.  Note that
the RFC we cite for idn-email, 6531, explicitly extends the
syntax from 5322.  This brings them into alignment.
=> Fix email RFC reference

jsonschema-core.xml
This commit fixes wording in Annotation section in json-schema-core.
**(Before)**
Unless otherwise specified, **the value of an annotation keyword's annotation** is the keyword's value. However, other behaviors are possible.
**(After)**
Unless otherwise specified, *the value of an annotation keyword* is the keyword's value. However, other behaviors are possible.
=> Fixing Wording in Annotation Section

jsonschema-validation.xml
Fixes #803.  See [this comment](https://github.com/json-schema-org/json-schema-spec/issues/803#issuecomment-589497630) for an overview of what is going on.
The reference to RFC 2045 was ambiguous and misleading.  Emphasize
RFC 4648 more, and clarify what from 2045 is relevant and when.
Also improved wording around the default behavior, lifting the notion of an
identity encoding from RFC 2045.
=> Improve contentEncoding RFC references

jsonschema-core.xml
This commit fixes wording in
* Annotations and Assertions
* The JSON Schema Core Vocabulary
=> Fix Wording in JSON-Schema Core

meta/applicator.json
While doing meta validation of the proposed OAS 3.1 meta-schema, I got an unexpected error that turned out to be caused by an error in the Draft 2019-09 applicator meta-schema for `unevaluatedProperties`. The OAS 3.1 meta-schema uses `"unevaluatedProperties": false`, which failed meta-validation because `false` is not an object.
=> Fix applicator meta-schema for unevaluatedProperties

jsonschema-core.xml, jsonschema-validation.xml
This will allow submitting multiple PRs that edit the changelog
without causing merge conflicts as long as they each add their
log entry to different list items.  We'll remove any leftover
empty items before publication.
=> Placeholder changelog

jsonschema-core.xml
This uses the US-ASCII part of the production.
See: https://www.w3.org/TR/2006/REC-xml-names11-20060816/#NT-NCName
=> Fix $anchor plain name format to match XML's NCName production

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
it doesn't seem to me to make sense that these are links. there is no document to retrieve. if you follow the link, it just links back to the same sections of the spec the link came from.
=> [suggestion] don't link vocabulary URIs; they are not retrievable

meta/core.json
This was missed in the $anchor specification update.
=> Fix $anchor pattern in core.json

jsonschema-core.xml, jsonschema-hyperschema.xml
Validation was updated a while ago, and relative json pointer
is being updated in another PR that is currently open.
=> Update years on core and hyperschema

jsonschema-core.xml, meta/applicator.json
Closes #810 (`unevaluatedItems` should consider `contains`)
Closes #864 (split `items`)
This reworks the array applicators in several ways:
* "prefixItems" takes on the former role of the array form of "items"
* "items" keeps its single-schema role, and takes on the role of
"additionalItems" when "prefixItems" is present
* "contains" now produces an annotation indicating what it evaluated
* "unevaluatedItems" now respects "contains", and the language around
interpreting the relevant annotation is (hopefully) less convoluted
Note that this does not address the change to put unevaluatedItems
into a separate vocabulary with unevaluatedProperties, which will
be done as a separate PR.  Doing that will also take care of the current ordering
problem- `contains` should appear before …
=> Split "prefixItems" from "items", drop "additionalItems", make "unevaluatedItems" respect "contains"

jsonschema-core.xml
Closes #808, closes #850 
`$schema` is now definitively resource-scoped rather than
document-scoped, as crossing a resource boundary is the same as
following a `$ref` to an external resource.
=> $schema can change across embedded resources

relative-json-pointer.xml
Closes #115 (to the extent that it is being adopted- several proposals came and went in that discussion).
This allows using a relative pointer to look ahead or behind
in arrays when calculating the initial point at which to apply
the JSON Pointer that is the suffix of the Relative JSON Pointer.
=> Rel JSON Ptr forward/backward index manipulation

jsonschema-core.xml
Closes #809 (technically only 1/3, the other 2/3 are fixed in #930, which is mostly about other things)
"Boolean Logic" is a better heading than "Logic" but its too long and breaks the table of contents link in the IETF HTML rendering.
=> Shorten long section heading.

hyper-schema.json, jsonschema-core.xml, links.json, meta/applicator.json, meta/content.json, meta/core.json, meta/format.json, meta/hyper-schema.json, meta/meta-data.json, meta/validation.json, schema.json
Closes #909 (improve/simplify/rename `$recursive*`)
Closes #868 (Let's not require runtime base URI tracking)
Also addresses 2/3 or #809 (overly long section names) but the other 1/3 is not in this part of the spec so I'll close that separately.
Instead of using a boolean (which never really fit with how the similarly named "$anchor" worked, and meant only one dynamic resolution was possible at a time) and messing with base URIs and re-resolving URI-references (a topic that creates plenty of confusion even on its own), use a fragment name the same as "$anchor" and make "$dynamicRef" work by just looking for the outermost resource with a matching "$dynamicAnchor" fragment name.
This stil requires that the initial "$dynamicRef" target URI be a valid URI, with a fragment created by …
=> Rename $recursive* to $dynamic*, make it work with normal anchors / plain name fragments instead of base URI switching

output/schema.json
Fixed some errors in output/schema.json
=> output schema fixes

meta/core.json
The spec allows values of false. This fixes the schema to match the spec.
Closes #954
=> [954] Fix $recursiveAnchor in schema to match spec

meta/applicator.json, meta/core.json, output/schema.json
These schema fixes have been made in master and not yet applied to the 2019-09 branch.
=> missing updates to existing 2019-09 metaschemas

jsonschema-core.xml
As amply explained by this very document, the "schema" media type parameter is
not legal with the "application/json" media type.
=> fix media type in examples

jsonschema-core.xml
=> Clarify how JSON Schema works with a superset of the defined data model

jsonschema-validation.xml
Fixes #959.
Don't say "that section" when we referenced two sections.
=> Fix ambuguity in RFC 3339 reference.

jsonschema-core.xml
Fixes #837.
This is to handle the case of schema objects embedded in
documents such as OAS documents, particularly when the object
is not an embedded schema resource.  This holds when the object
is a schema resource as well, but in that case the base URI is
immediately overridden by "$id".
=> Initial base URI for embedded objects.

jsonschema-core.xml
Fixes #990, plus other minor cleanups in separate commits.
* Fix missed "$id" to "$anchor" change and related wording
* Fix indentation
* Make the number in the text match the number of items in the list of keyword classifications
=> Fix missed "$id" that should be "$anchor", and other minor fixes

jsonschema-validation.xml
Fixes #948.
Also updates a missing `prefixItems`.  Fix this by just not being so detailed about special cases and make the general usage more clear, noting that it can produce some odd scenarios.
`deprecated`, like all annotations, is intended to be handled by applications rather than JSON Schema implementations so there's not a ton of practical impact with this.
=> Clarify how "deprecated" works w/arrays & objects

jsonschema-core.xml, jsonschema-hyperschema.xml, jsonschema-validation.xml
Fixes #988 and other inconsistencies regarding empty fragments.
@Relequestual regarding the issue and empty fragments you [wrote](https://github.com/json-schema-org/json-schema-spec/issues/988#issuecomment-688483240)
> The spec says "MUST NOT have an empty fragment".
The exact wording of the [spec](https://github.com/json-schema-org/json-schema-spec/blob/2747ab4a506af937117a92cf35acce3880438a53/jsonschema-core.xml#L1330) with respect to `$id` (not `$schema`) currently is
>  "$id" MUST NOT contain a non-empty fragment, and SHOULD NOT contain an empty fragment.
I guess you referred to this part of the spec since I could not find any other mentioning of empty fragments. I read this as
- `http://example.com/my-schema-id#non-empty` must not be used
- `http://example.com/my-schema-id#` should …
=> Fix 988 - Inconsistencies with schema uri and empty fragment URIs

hyper-schema.json, jsonschema-core.xml, meta/applicator.json, meta/unevaluated.json, schema.json
Fixes #853.  Fixes #831.
Quite some time ago we agreed to split these out.  Now support (or lack of support) is all handled through `$vocabulary`, without any "the vocabulary is supported except these keywords might error out if the implementation just didn't feel like it" behavior.
If the implementation doesn't support annotations, it won't be able to process anything that requires the unevaluated vocabulary.
=> Split "unevaluatedItems" and "unevaluatedProperties" into their own vocabulary.

jsonschema-core.xml, jsonschema-validation.xml
Fixes #902.
This gets the term introduced.  I am leaving out hyper-schema
for now as we don't plan to update it soon.
=> Put "dialect" in the spec.

jsonschema-core.xml
And try to avoid memory exhaustion attacks, which were possible
even with out this change but potentially more likely to happen
by accident with it (e.g. unrecognized applicator with a very
large subschema).
Fixes #698.
=> Collect unknown keywords as annotations

jsonschema-core.xml
Fixes #906.
The approach of annotation keywords specifying combination rules
is not really compatible with the output format approach.  It is
also a source of uncertainty in how to use and specify annotations.
This removes the concept.  Note that "readOnly", "writeOnly", and
"deprecated" still advise applications on how to handle multiple
values.  However, the wording is purely in terms of application
handling and not in terms of aggregating the values, so no change
to the validation spec is necessary.
=> Remove special case handling of annotation values

jsonschema-core.xml
A prefix of zero length makes no sense.
Fixes #975, thanks @karenetheridge!
=> The value of prefixItems MUST be non-empty

output/schema.json
1. Changing "oneOf" to "anyOf", because basic, detailed and verbose have the same definition, oneOf would fail validation.
2. Adding "error" keyword and making either "error" or "errors" required in case "valid" is false.
=> Issue-949: Fixing inconsistencies in output schema

jsonschema-core.xml
It is like absolute filesystem paths, not like absolute-URI
from RFC 3986.  In fact, an absolute keyword location can
never be an RFC 3986 absolute-URI because a fragment must always
be present to identify the keyword.
_**NOTE**: this PR is **not** for any discussion of renaming fields in the output format, since someone always wants to rename something.  If you want to rename something, get consensus around it and file it as a new issue/PR.  Do not raise it here._
=> Clarify what "absolute" means for keyword absolute location

jsonschema-core.xml
Define Compound Schema Document and associated concerns
Resolves #936
=> Define compound schema documents (#936)

jsonschema-core.xml, jsonschema-validation.xml
Fixes #821
Reference specific version of emca262.
=> Reference ECMAScript 11.0 specifically (#821)

jsonschema-core.xml
According to the main ECMA-262 page, the link needs an "index.html" suffix.
There's no guarantee that linking to the raw "11.0/" directory will lead to
the correct place, even if it does. This updates to the correct well-known
link. Not all sites necessarily support a default page for an empty path
suffix; it is not correct to remove the last part.
Ref: https://www.ecma-international.org/publications/standards/Ecma-262.htm
=> Fix ECMA-262 link

jsonschema-core.xml
=> Clearly define a dialect

jsonschema-core.xml
..because now, we collect unknown keywords as annotations, and this behaviour
is explicitly prohibited for $comment.
=> it is no longer valid to treat $comment as an unknown keyword

jsonschema-core.xml
=> Attempt to justify and explain unevaluated keyword phrasing

meta/core.json
I appears this was missed when updating the meta-schemas to use `$dynamicRef` and `$dynamicAnchor`.
=> Fix "dynamic" keywords in core vocabulary meta-schema

jsonschema-validation.xml, meta/format-annotation.json, meta/format-assertion.json
There is also this in the "Custom format attributes" section below the edits:
> An implementation MUST NOT fail validation or cease processing due to an unknown format attribute.
What is an implementation to do when an unknown format is encountered other than fail?
The context may be around collecting annotations, but it says "validation," so I'm confused.  Maybe this needs to be clarified a bit too.
---
Resolves #1020.
Closes #1023.
Closes #1026.
=> `format` as a annotation by default - separate vocabs (option 3)

jsonschema-core.xml
Resolves parts of #1032
Modify some requirements and language relating to compound schema documents based on feedback in #1032.
Allow embedded schema resources to use relative URIs as opposed to just absolute URIs.
Reference dialect rather than in terms of processing requirements for embedded resources which don't specify their dialect.
=> Update or fix some aspect of compound schema document bundling

jsonschema-core.xml
Specify that other keywords may load or inspect instance data in other locations
Fixes #855
=> Keywords may look at instance data

jsonschema-core.xml, jsonschema-validation.xml
Fixes #924 
Clarify contains when applying to an empty array, annotation results, and how they are used
=> Clarify contains when applying to an empty array

jsonschema-core.xml
This PR fixes errors in the spec for the dynamic and keywords and dynamic scope. The spec describes dynamic scope to only be resolvable when processing an instance. This wasn't true for the recursive keywords, and it isn't true for the dynamic keywords either. You need to know all the schemas and how they reference each other, but you don't need an instance. The vast majority of these changes cover that issue. The rest fixes minor typos and such.
=> Fixes for dynamic scope and keywords

jsonschema-validation.xml
I feel this change makes the descriptions easier to parse and to digest. I also swapped "instance" and "array" because this is really an "array belonging to an instance" and not an "instance of an array."
Fixes #1044
=> [1044] Improve "maxContains" and "minContains" descriptions

jsonschema-core.xml
Since this is mostly reverting, I added https://github.com/jdesrosiers/json-schema-spec/commit/321d3841631adb2514277f03f5d112af98b681cf to show what the actual diff is from the original spec. It's mostly typo fixes and removing a couple crefs.
The original PR was https://github.com/json-schema-org/json-schema-spec/pull/1041
=> Revert changes to dynamic scope regarding dependence on instance

relative-json-pointer.xml
=> Rel JSON Pointer: add ABNF/examples for index manipulation

meta/applicator.json, meta/content.json, meta/core.json, meta/validation.json, schema.json
=> Meta-schema 2020-12 update

schema.json
Missed this at first, but found it when updating my implementation.
=> added unevaluated meta-schema to allOf list in primary meta-schema

jsonschema-validation.xml
Fixes https://github.com/json-schema-org/json-schema-spec/issues/1080
I adjusted the wording suggested in the issue, so let me know if anyone thinks it doesn't read clearly enough.
=> Improve wording for the type keyword in the spec

jsonschema-core.xml
Per #1089 we don't need to repeat this in every vocabulary section, just in the opening sections (8.1.3).  Also includes a separate commit updating the year in all of the active specs.
=> Remove repetitiously redundant paragraphs

jsonschema-core.xml
Fixes #1058.  I think there is agreement on this?  It was faster to write a PR than ping the issue.  I'm not attached to this wording if folks prefer something else.
=> Vocabulary definitions need not be formal or published depending on usage.

jsonschema-core.xml, jsonschema-validation.xml
Resolves https://github.com/json-schema-org/json-schema-spec/issues/1077
The two ways to go with this were to have `contains`/`minContains`/`maxContains` apply to objects, or to introduce three new keywords that apply to objects. I went with the first option because that was the only one anyone expressed a preference for and no one objected.
=> Allow contains to apply to objects as well as arrays

jsonschema-core.xml, meta/core.json
This would add support for IRI references in $id, $ref and $dynamicRef as per #59.
This PR fixes history of #1068.
=> Support for IRI references

jsonschema-validation.xml
It is related to MIME's Content-Transfer-Encoding, and not
HTTP's Content-Encoding.
Fixes #1100
=> Clarify the origin of contentEncoding

jsonschema-core.xml, jsonschema-validation.xml, meta/applicator.json, meta/content.json, meta/core.json, meta/format-annotation.json, meta/format-assertion.json, meta/meta-data.json, meta/unevaluated.json, meta/validation.json, output/schema.json, schema.json
...so implementations can start testing with them
=> update schema identifiers to "draft/next" everywhere

jsonschema-validation.xml
- minor clarification on http's Content-Encoding
=> Nitpick content-encoding. See #1100

jsonschema-core.xml
Resolves https://github.com/json-schema-org/json-schema-spec/issues/1064
Discussion about changes to `$dynamicRef` behavior are still on going, but I want to capture the part that we did get consensus on, which is to remove the bookending requirement.
=> Remove bookending requirement for dynamicRef

jsonschema-core.xml
We also remove the trailing comma.
See: https://github.com/json-schema-org/json-schema-spec/pull/1162
=> Add missing closing curly brace to D.2. example

Makefile
It is a best practice to allow callers to override the value of these
program variables. For example, with this chance, you can do:
```sh
make XML2RFC=/opt/bin/xml2rfc
```
See: https://www.gnu.org/software/make/manual/make.html#Command-Variables
=> Allow the XML2RFC GNU Make variable to be overridden by the caller

jsonschema-core.xml, jsonschema-validation.xml
This is an amended and abridged version of the changes proposed in #1110. This only contains clarifications; any changes to behaviour must be reserved for a future specification revision.
=> wording fixes for the interim release

jsonschema-core.xml
The "schema" media type parameter got removed for the 2020-12 release, but some of it was missed. This removes the remaining bits.
Reference: https://github.com/json-schema-org/json-schema-spec/issues/832
=> Remove remaining media-type param references

jsonschema-core.xml
=> Clarify that plain name fragments are neither canonical or non-canonical

jsonschema-core.xml
Fixes https://github.com/json-schema-org/json-schema-spec/issues/937
I [screwed up a force push](https://github.com/json-schema-org/json-schema-spec/pull/1104#issuecomment-1066700685) on https://github.com/json-schema-org/json-schema-spec/pull/1104 so this is the replacement.
Will contain the same commits.
Extract from the first comment on #1104 
> Fixes issue https://github.com/json-schema-org/json-schema-spec/issues/937, clarifying a number of other things along the way.
> While it touches a fair number of lines, I'm fairly sure that it
> doesn't anything about conformance.
> 
> [NOTE: This does not address the question of whether "canonical" is what we want - that is too large of a change for a https://github.com/json-schema-org/community/discussions/7 which is what this PR is targeted …
=> Clarify various things about canonical URIs

schema.json
Keywords from draft2019-09 are intended to be silently accepted (with a deprecated annotation), not cause validation failure.
=> fix the type for $recursiveAnchor

jsonschema-core.xml, meta/applicator.json
Resolves https://github.com/json-schema-org/json-schema-spec/issues/1082
I tried to match the language used for `dependentSchemas` as much as possible given the similarity between the two keywords.
=> Add propertyDependencies keyword

adr/2022-04-08-cref-for-ambiguity-and-fix-later-gh-spec-issue-1172.md, adr/README.md, adr/template.md, jsonschema-core.xml
Fixes #1172
Must see new issue relating to the behaviour of annotation collection for resolving in the next draft.
Related to https://github.com/json-schema-org/community/discussions/57
=> Add CREF about ambiguous behaviour of additionalProperties

jsonschema-core.xml, output/verbose-example.json
This PR is the start of changes to the output format as discussed [here](https://github.com/json-schema-org/community/discussions/63).
It covers changing property names:
- `keywordLocation` -> `evaluationPath`
- `absoluteSchemaLocation` -> `schemaLocation`
- `errors`/`annotations` -> `nested`
(In making these edits, I began to see why so many people were asking for examples with annotations.  I expected that to be a trivial exercise given the error examples, but I get it now.)
=> Changing property key names in output format

relative-json-pointer.xml
It is currently not possible to build the Relative JSON Pointer's spec.
`xml2rfc` will complain about the date tag not being the current year
while not having a month set either.
This is the error I get:
```
xml2rfc --html relative-json-pointer.xml -o relative-json-pointer.html
json-schema-spec/relative-json-pointer.xml(16): Error: Expected <date> to have the current year when month is missing, but found '2021'
Unable to complete processing relative-json-pointer.xml
```
This PR changes the `<date/>` year to the current year.
=> Add month to Relative JSON Pointer's spec <date/>

jsonschema-core.xml
Fixes the build errors -- I don't know how this stuff works and/or whether this has to do with upstream changes or some normalization that's happening, but this does seem to work here at least now.
=> Update the xrefs, which appear now to have underscores

.github/workflows/ci.yml, .travis.yml
The GitHub Actions setup is equivalent to the Travis CI configuration
with two differences:
- The GitHub Action setup does not set the `TAG` environment variable,
as it didn't seem like `xml2rfc` would consume that at all (unless I'm
missing something)
- The GitHub Action preserves the spec output (txt and html) as
artifacts that can be downloaded after a successful run (to see the
changes without having to locally render the specs)
Fixes: https://github.com/json-schema-org/json-schema-spec/issues/1262
=> Replace defunct Travis CI integration with GitHub Actions

jsonschema-core.xml
I noticed a few places where the spec is using several different phrasings to mean the same thing.  This PR aligns them to what we agreed it should be called in the output.
=> align path terminology in the text with the renamings made for the output

jsonschema-core.xml
This is just a bug fix for an accidental oversight.  I'm hoping it's non-controversial as I don't think any of us meant to allow arbitrary behaviors for unrecognized keywords.
When we added the "SHOULD collect as annotations" behavior for
unknown keywords, we forgot to retain the MUST directive to ignore
them if the SHOULD is not followed.  Which also ensures that
no other behavior than collecting as a annotations is performed.
This also consolidates the behavioral specification in one place
as it appeared in two places before.
=> Ignore unknown keywords or treat as annotations

relative-json-pointer.xml
=> Defines what happens when relative JSON pointer starts with zero

jsonschema-core.xml
Fixes issue #1271 and addresses one point mentioned in https://github.com/json-schema-org/json-schema-spec/issues/1059#issuecomment-1212726799 (but please do not drag the rest of that issue into this PR, thanks!)
The only actual changed requirement is the forbidding of `"$id": "#"`, and `"$id": ""` which are confusing and are either pointless (in a document root where they resolve to the retrieval IRI, exactly as if `$id` was not present) or problematic (in an embedded resource root, where they produce duplicate IRIs for the embedded and containing resource).
This also consolidates the two different places where duplicate IRIs were addressed.  Since the more general of the two paragraphs stated that this SHOULD be an error, I kept the SHOULD rather than the MAY that addressed only a …
=> Consolidate and clarify language around duplicate IRIs

jsonschema-core.xml
Now there's a dot between W3C and the rest, and the underscores are back to hyphens.  Apparently.
Previously changed in PR #1268
=> xref format changed again - fix broken build

jsonschema-core.xml
This was just an oversight regarding where $vocabualry is legal. It should have always been "schema resource root."
Fixes #1129.
=> Missed a "schema document" -> "schema resource"

adr/2022-08-decouple-from-ietf.md
Here's a fist draft for an ADR for decoupling from JSON Schema. I'm sure it needs some cleanup and fleshing out in places. I'll revise tomorrow.
The scope of this ADR is decoupling from from IETF. That doesn't include the decision to stop using "draft", but enables us to make that decision later.
=> Add ADR for decoupling from IETF

jsonschema-core.xml
=> Clarify prefixItems wording about array length

jsonschema-core.xml
Because XML is/was the most likely need for cross-media-type fragment identifiers.
Fixes #901
=> Explain why plain name fragments are as they are

jsonschema-core.xml
=> Note non-anchoring of regexes in the regex section.

jsonschema-core.xml
I think this is probably what was intended - I don't see any reason for the arrays in this example to be nested. If I'm wrong and this is how the schema is supposed to be, the reference [here](https://github.com/json-schema-org/json-schema-spec/blob/draft-bhutton-json-schema-01/jsonschema-core.xml#L1747) to the schema containing the `#item` reference should be corrected from `#/items` to `#/items/items`.
Introduced [23ba42e1](https://github.com/json-schema-org/json-schema-spec/commit/23ba42e1#diff-bda51aab56b4b2e23fc9e7249e80fe6e262dcd552f35c5de69fd4a6bf3e96b50R417-R419) - ping @awwright, not that I expect you to remember these lines six years later.
=> Core#Dereferencing example schema: remove second dimension of array

jsonschema-core.xml, meta/core.json
Fixes the "$id" side of #1059, as @jdesrosiers was the only objector to that part and eventually [dropped his alternate proposal](https://github.com/json-schema-org/json-schema-spec/issues/1059#issuecomment-761151057).
Note that, syntactically, this is backwards-incompatible, but it is a change that we warned about in the CREF for the last three I-D publications, which ought to be sufficient warning.
=> Disallow fragments in "$id"

jsonschema-core.xml, jsonschema-validation.xml, meta/applicator.json, meta/validation.json
Fixes #1311.  Fixes #1161 by eliminating the confusing situation that produced the concern.
=> Reverse "contains" <-> "minContains"/"maxContains" dependency

LICENSE, README.md
Historically JSON Schema has declared that contributions are licensed
BSD or AFL, without specifying the version of BSD. We’ve been
asked to specify a version for work elsewhere in the ecosystem, and
OpenJS Foundation counsel recommended BSD 3-clause as the most common
choice. This commit clarifies the specific versions (3-clause and v3.0
respectively), and adds a LICENSE file to make this explicit.
See https://github.com/json-schema-org/json-schema-spec/issues/1160#issuecomment-1123583441
for the full guidance.
Per the guidance, we'll leave this open for a few weeks (perhaps till August 31?) in case there are comments from any historical contributors, who I'll also now ping (with apologies to those of you who aren't interested). @fge @kriszyp @geraintluff @nickl- @garycourt.
SPDX short …
=> Specify the specific BSD and AFL versions this repo is licensed under.

.gitignore, Makefile, README.md
It's common to make a virtualenv inside of your cloned repo
to ensure that you have the right enviornment for that repository,
and .venv is a common convention for that virtualenv.
This adds targets to create and clean a .venv virtual env using
the checked-in requirements.txt file.  It also adds the .venv
to the .gitignore, and updates the README.
=> Make targets for a virtualenv

jsonschema-core.xml, jsonschema-validation.xml, relative-json-pointer.xml
This gets rid of all of the build warnings except the ones for the lines being too long, which aren't worth trying to fix as we're changing formats anyway.
But these are simple fixes to remove everything else. As of RFC 7749 (xml2rfc v2 vocabulary), the RFC 2629 DTD is no longer needed.  The submissionType was also added then.  It is supposed to default to "IETF" but apparently newer versions of xml2rfc no longer do this.
I don't know why xml2rfc did not like the no-breaking space in the xref, but it's happier with it gone.
=> Fix a lot of build warnings (only 7 lines of changes)

.github/workflows/pr-dependencies.yml
I use this on my `json-everything` repo (and I've used in it a few other places) to track when PRs are dependent upon each other.  For example, how #1285 is dependent upon #1085.
https://github.com/marketplace/actions/pr-dependency-check
=> add pr-dependencies-check workflow

jsonschema-validation.xml
This feature added substantial complexity and security exposure for essentially no benefit. The functionality could be trivially implemented as a library on top of a JSON Schema implementation that supports annotation collection.
Fixes #1287.  Intentionally avoids topics still under discussion in #1288.
=> Disallow even optional "content*" processing

output/schema.json
Updates the output schema file to match the new structure as described by the specification.  Follow-up to #1249.
I've tested this against the example output in the spec.
Resolves #949
=> Update output schema to describe new structure

jsonschema-core.xml
Fixes #1313.  The idea of annotations and applicators interacting is outdated. Annotation deletion/dropping occurs at the schema object level (clarified in recent drafts), and annotation values have not defined aggregation semantics within JSON Schema evaluation since draft-07.
=> Remove annotation-applicator interaction section

jsonschema-core.xml, output/schema.json
Partially addresses #1319.
This adds `droppedAnnotations` to the output unit as an optional field.  While they can be useful for debugging, these annotations are usually just noise.
=> add droppedAnnotations

CONTRIBUTING.md
I copied this file over to the referencing spec and was informed it was out of date, so here's a backport of the update.
=> Update code of conduct in CONTRIBUTING.md

jsonschema-core.xml
Resolves #1310 
Improves the annotation definition language for `properties` and `patternProperties`.
`properties` - replaced "match" language to be more explicit
`patternProperties` - clarified "match" language
=> Update `properties` and `patternProperties` annotation language

adr/2022-11-stable-spec.md
Resolves: https://github.com/json-schema-org/json-schema-spec/issues/1333
Here's the ADR for documenting the reasons for the paradigm shift in how we develop the spec. I included the approach @awwright laid out recently, but I don't see that so much as an alternative as complementary. If we decide we want to work toward that vision, it would fit just fine into the process we have been discussing and have agreement on.
=> Add ADR for choosing a new SDLC

jsonschema-validation.xml
* Minimally fixes #1288 (as [noted](https://github.com/json-schema-org/json-schema-spec/issues/1288#issuecomment-1322612454), other ideas in that issue can be filed separately for further discussion).
* Fixes #1307 
[note: The fix is shorter than this description]
The value of `"contentSchema"` is a normal subschema, and using it out of context can fail in ways schema users are unlikely to automatically consider.  Since `"contentSchema"` has to be applied separately from the evaluation process in which it was collected as an annotation, it is schema authors and users (rather than implementers) who need to be aware of this.  In particular, users need to know the safe way to access the schema.
We know that many schema users find base URIs/IRIs confusing, and that the behavior of …
=> Clarify how to use "contentSchema"

jsonschema-core.xml
Fixes #1315 
This may well change prior to the next release, but documents the intended range of options so as to avoid crashes or completely arbitrary behavior.  I believe it covers the observed behavior of implementations in the wild, so even though there is a new MUST I don't think it would cause a problem.
=> Put boundaries on lack of "$schema" behavior

jsonschema-core.xml
This shouldn't cause any changes except that "Section" or "Appendix" text is now included as part of the link.
@handrews I think you wrote all of these cases, can you double check?
=> Remove some superfluous format="counter" attributes

jsonschema-core.xml
This updates the syntax to the v3 vocabulary which is what the Markdown toolchain generates. This should be pulled in before #1369, #1370.
=> Upgrade to rfc2xml v3

jsonschema-core.xml
Resolves #1321
I'm not sure how far we want to take this.  Should implementations check vocabulary extensions to ensure they don't define `$` keywords and throw an error if they do?
=> reserve dollar keywords for core vocab

jsonschema-use-cases.xml
This is a document I've been working on for a little bit that I think would be very relevant to some of the discussion right now.
We're trying to figure out what parts of the specification are "stable," but (IMO) stability is something that you determine _with respect to a particular use case._ An example I pointed out earlier, if I publish a GPU-intensive program that stops being effective as a space heater because I improved the algorithm, too bad for you because it was never "stable" for home heating purposes, only cat detection purposes (or whatever).
This document would describe the use cases that we actually intend to support; when we make changes to the specification, we can point to this document and say "this feature in Use Cases would break if we made this change." Or we can …
=> Use Cases and Requirements document

.github/workflows/minimum-open-time.yml
Currently, this needs to be manually re-run.  It'll run automatically on new commits, though.
=> add minimum open time action for PRs

adr/2023-04-sva-prefix.md
Related to https://github.com/orgs/json-schema-org/discussions/329
(This is my first ADR.  Please be gentle. 😆)
=> Create ADR for SVA support

relative-json-pointer.xml
Replaces #1361 
~Adds an optional index manipulation to the syntax.~
It looks like this was already in the text, but the ABNF was just missing it.  This PR adds the missing syntax into the ABNF.
=> Updates for Relative JSON Pointer

relative-json-pointer.xml
In order to publish a new RJP draft per agreement (@gregsdennis), I needed to make a few changes due to updates in the publishing requirements and restrictions on re-use of draft numbering sequences.  This aligns the XML file with the published [draft-hha-relative-json-pointer-00](https://datatracker.ietf.org/doc/html/draft-hha-relative-json-pointer-00).
=> Updates that were needed in order to publish RJP

.github/SECURITY.md
Resolves https://github.com/json-schema-org/community/issues/351
We have already previously enabled security reporting on the spec repo.
While I made it clear that people should not report impelementation security concerns here, I wanted to also offer potential help to implementers who might get reports.
I can't imagine we would get any reports given the repos/projects we currently have, although that could change in the future, and this is a requirement of the OpenJS Foundation onboarding process.
=> Add security policy document

build/remark-code-titles.js
The remark-code-titles plugin adds styling for JSON Schema and JSON code blocks. This adds support for JSONC as well, styling it the same as JSON.
=> Remark build: Style JSONC code titles as JSON

jsonschema-core.md
This is in prep for extracting the output sections into their own spec in order to support multiple outputs for different purposes (cc: @karenetheridge).  I expect this to take place over several PRs, but #1385 shows the gist of the end goal.
=> markdown errata

jsonschema-core.md, jsonschema-validation.md
Replaces #1360.  Updated for markdown.  See that PR for dicussions.
=> Add all changse since last release to Change Log (markdown version)

jsonschema-core.md
Replaces #1359.  Translated to markdown.
See that PR for discussion.
=> Plain name IRI fragments can use unicode (markdown version)

jsonschema-core.md
=> require `$schema` in schemas

jsonschema-core.md
Resolves #898 
After wordsmithing something that sounded approximately right, I found [Instance Equality](https://json-schema.org/draft/2020-12/json-schema-core.html#name-instance-equality), which pretty much clears up any debate in my mind.
=> remove 'mathematical integers' section

jsonschema-core.md
Resolves https://github.com/json-schema-org/json-schema-spec/issues/1276
I think I've captured the intent of comments in the issue.  Happy to make adjustments.
=> add section to specify behavior for failed reference resolution

meta/applicator.json, meta/content.json, meta/core.json, meta/format-annotation.json, meta/format-assertion.json, meta/hyper-schema.json, meta/meta-data.json, meta/unevaluated.json, meta/validation.json
Relates to [Discussion #511](https://github.com/orgs/json-schema-org/discussions/511).
=> remove `$vocabulary` from vocab meta-schemas (2020-12)

jsonschema-core.md
Resolves #1358
Relates to #1444
I think I got everything, but maybe another pair of eyes could help.
=> Revert "`contains` applies to objects"

.github/FUNDING.yml
As of now the button to sponsor on Github is not working in this repo because if this file. We have org wide version in the .github repo and if we remove this we'll have the consistent setup applied accross.
=> Remove the funding file to use the org wide settings.

adr/2024-02-object-contains.md
@karenetheridge noted that there wasn't an ADR for this, and I agreed there probably should have been.
Relates to https://github.com/json-schema-org/json-schema-spec/issues/1077 and https://github.com/json-schema-org/json-schema-spec/issues/1358.
=> add adr for 'object contains'

PROCESS.md, proposals/proposal-template.md
Resolves #1443 
I started working on the `propertyDependencies` extraction and the template kinda just worked itself out.  It turns out leaving questions is easier that actually filling out the sections.
=> add proposal document template

adr/2024-05-08-extract-unstable-keywords.md
As [mentioned](https://github.com/json-schema-org/json-schema-spec/issues/1443#issuecomment-2099429276), this ADR documents the decision to extract unstable keywords prior to stable spec release.
This is to support [this proposal](https://github.com/json-schema-org/json-schema-spec/issues/1443#issuecomment-2099427543) of including an ADR alongside proposal documents.
=> Add ADR for extracting unstable features

.gitignore, README.md, build/build.js, jsonschema-core.md, package.json, proposals/propertyDependencies-adr.md, proposals/propertyDependencies.md
This is a second attempt at #1450.  Rather than start from scratch, I build upon that because I wanted to keep the build changes that @jdesrosiers made.
The idea here is that the proposal document is something that the users will be concerned about, including both a summary of why the proposal is being made and the specific changes to official documents.
There will also a be separate "decision" document (not yet added), which may just be an ADR, that goes through why this solution is being proposed, including pro/con analysis of any alternative designs.  We'll continue discussing in #1443 about what this secondary document looks like.
=> Extract `propertyDependencies`

adr/template.md
Asked about this in [Slack](https://json-schema.slack.com/archives/C05FQEMV8V6/p1715641220390059) and got no sustainable objections.
Happy to discuss more.
This arrangement just makes more sense to me.
=> update adr template to merge pros/cons and option descriptions

jsonschema-core.md
Holding this PR based on the outcome of https://github.com/orgs/json-schema-org/discussions/491
Related to #1444
=> add section about keyword interaction mechanics being illustrative

CONTRIBUTING.md
Summary: This file is a brand new version of the contributing file to remove outdate information.
Resolves https://github.com/json-schema-org/json-schema-spec/issues/1414
=> Update CONTRIBUTING.md to remove outdated information

jsonschema-core.md
Add "." to the permitted simple atoms, for issue #1469.
Consistently format the regex examples.
=> Regex editorial improvements, and permit "."

jsonschema-core.md
Fixes https://github.com/json-schema-org/json-schema-spec/issues/1480 to omit the sentence about omitting the keyword, as `allOf` etc do.
Also fixes a small markdown error while I'm touching that section.
=> Fix `prefixItems` keyword omitted behavior

jsonschema-core.md
per the "Evaluation path" section stating "The value MUST be expressed as a JSON Pointer"
=> Evaluation path example fix to use pointer rather than URI fragment syntax

jsonschema-core.md
Per [this Slack thread](https://json-schema.slack.com/archives/CT7FF623C/p1717978845635409), we felt that the wording here doesn't do enough to describe "x-" keywords as "known" keywords.
=> Improve "x-" keyword description

jsonschema-core.md
We discussed this a lot, but never actually made the changes.
Resolves #1340
Resolves #1365
=> Remove support for unrecognized keywords

jsonschema-validation.md
clarify that `readOnly` applies to any value, not just properties.
Re-format `true` and `false` code values
Resolves #1402
=> Fixes #1402: clarify `readOnly` applies to any value, not just properties

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/clarification.yml, .github/ISSUE_TEMPLATE/proposal.yml, .github/PULL_REQUEST_TEMPLATE.md
I'm not completely set on these.  Happy to change them if needed.  It's just something thrown together to get started.
Probably doesn't need the 2w minimum time.
=> update issue and pr templates

jsonschema-core.md, jsonschema-validation.md, proposals/vocabularies-adr.md, proposals/vocabularies.md
Relates to https://github.com/orgs/json-schema-org/discussions/724 and https://github.com/json-schema-org/json-schema-spec/pull/1505.
Depends on #1518
Depends on #1512
(will likely need rebase after those merge)
The Core spec was a lot, but it was fairly straightforward.
This PR will make a best effort to include vocabularies as they are in 2020-12 as a start.  Some redesign is inevitible, but this this is a good starting point.
=> Extract vocabularies from the specs

jsonschema-core.md, jsonschema-validation.md
Cleans up some language around `$id`.
- Related to #1444
- Related to #1349
Just some clean-up and clarification that we've previously identified.
> Schema document roots SHOULD have an $id (maybe relax this? ...) - from https://github.com/json-schema-org/json-schema-spec/issues/1444#issuecomment-1749604538
I decided to leave this in for now.  We can discuss and change separately if needed.
No
=> `$id` updates

jsonschema-core.md
Clarification
-  Related to #1444 
The `if`/`then`/`else` keywords largely look good.  I thought this one spot could be a bit more explicit.
No functional change.
=> minor clarification for if-then-else

jsonschema-core.md
Updates for spec release
-  Related to #1444 
Updates the `unevaluated*` keywords and sections that reference them (e.g. "this keyword's annotation affects the behavior of this other keyword").
=> unevaluated* updates (and some annotation dependency cleanup)

specs/jsonschema-core.md
Clarification
-  Closes #1218 
Removes 2 redundant sections about keywords being independent.  We now have a "Keyword Independence" section, and each keyword section explicitly states their relations to other keywords.
No
=> remove redundant sections about keyword independence

.github/workflows/ci.yml
We got a notice that the version of `actions/upload-artifact` that we are using is going to be deprecated. This updates that action and other outdated actions to the latest version.
=> Update deprecated Github action

adr/2024-11-2-assertion-format.md, specs/jsonschema-validation.md
Feature update
Closes #1520 
Depends on https://github.com/json-schema-org/TSC/issues/19
Makes `format` an assertion to align with user expectations.
Quick notes:
- Implementations SHOULD support `format` with the defined values
- Implementations MAY support others, but only by explicit config
- Implementations MUST refuse to process a schema that contains an unsupported format
- Permissive allowances removed since every format is clearly defined by referencing a specification
Technically a breaking change, but aligns to user expectations. So... ????
=> make format validate by default

specs/jsonschema-validation.md
clarification
-  Closes #1404
Clarifies that `type` as an array must be non-empty.
Technically yes?  @awwright did point out that there is a niche use case as an alternative to `{not:{}}`, but the keyword certainly wasn't intended to be used this way.  Also, given that we present `{not:{}}` as the analog to `false`, it's extremely unlikely that anyone will be using it this way on purpose.
=> clarify that `type` must be a non-empty array

specs/jsonschema-core.md
clarification
-  Closes #1442
Clarifies that meta-schema validation applies to the schema _resource_ that declares the meta-schema with `$schema`.  Also adds a pointer to the section on validating compound documents to reinforce that meta-schema validation should be a special activity separate from applying a schema to an instance.
No.
=> clarify that a meta-schema applies to the schema resource, not necessarily the whole document

specs/jsonschema-core.md
clarification
- Closes #1390
- Related to #1274
Removes the text highlighting CBOR as an example compatible data format.  This is better placed in docs than the spec.
No.
=> remove reference to CBOR as a compatible format

adr/2024-11-2-assertion-format.md, specs/jsonschema-core.md, specs/jsonschema-use-cases.xml, specs/relative-json-pointer.xml
Clarification
- Related to #1444
- Replaces #1142
Cleans up the `$dynamic*` keywords.
Yes
=> clean up `$dynamic*`

specs/jsonschema-core.md
Editorial
-  Related to #1470
- Related to #599
- Related to 314b5c3040c5af13f838165189df3e0585b35a26
Referring to the difference between e.g. `.+` and `.+?` as "laziness" isn't wrong, but it is less accurate than "greediness".
No.
=> use more accurate regex vocabulary

specs/jsonschema-validation.md
clarification
-  Closes #1381 
-  Related to #1288 
Updates the text for `contentSchema` to indicate that its value is indeed a subschema (and therefore should be treated as such when scanning for identifiers).  Also cleans up language around its dependency on `contentMediaType`.
I didn't include any explicit text about it containing identifiers.  Instead I declare that the value _is_ a subschema and removed the "SHOULD ignore" text discussed in the issue.
Also pertinent to the issue discussion is the final couple sentences (already present), which I ~broke out into a new paragraph~ rewrote to make it more apparent that it is a note of guidance rather than a requirement.
> Accessing the schema through the schema location IRI included as part of the
> annotation will ensure that it is …
=> clarify that contentSchema holds a subschema and when/how it applies

specs/jsonschema-core.md
clarification
- Closes #1493
Clarifies what a keyword's annotation value should be.  Just language clean-up.
cc: @hudlow
No.
=> clarify what a keyword's annotation value is

specs/jsonschema-validation.md
clarification
- Closes #1573
Lowercases several MAY occurances that are incorrectly used.
No
=> lowercase unnecessary MAY usage

specs/jsonschema-core.md
Clarification
- Closes #1140
This is mostly cleanup building on #1555, although I rewrote a couple of parts I though needed it.
The main objective is to achieve consistent and correct usage of terms around fragment identifiers. Here are the definitions I'm using.
- **fragment identifier** -- This is an identifier for a secondary resource (subschema) within the primary resource (schema resource).
- **IRI fragment** -- The fragment identifier that appears after the `#` character in an IRI.
- **plain name** -- A specific type of fragment identifier. `$anchor` creates a plain name fragment identifier.
- **fragment-only IRI** -- An IRI that starts with `#` and is followed by a fragment identifier.
- ~**fragment**~ -- This term by itself is ambiguous and imprecise. I replaced all usages with a …
=> Additional cleanup for dynamic references

links.json
In Draft 4, `dependencies` is either a schema or an array of unique strings.
See: https://json-schema.org/draft-04/draft-fge-json-schema-validation-00#rfc.section.5.4.5
See: https://www.learnjsonschema.com/draft4/validation/dependencies/
=> Fix `links` not adhering to its meta-schema given invalid `dependencies`

specs/jsonschema-core.md, specs/jsonschema-validation.md
clarification
- Closes #1540
- Closes #1447
The previous language could imply that all keywords needed to have an assertion result, e.g. annotations would always produce a "true" assertion result.
For `min/maxContains`, I added explicit text that they do not produce an assertion result, emphasizing that the assertion comes from `contains` and that these keywords are informative.
This change clarifies that keywords only exhibit the behaviors they're defined with.
No.
=> keywords only exhibit the behaviors they're defined with

specs/jsonschema-core.md
…ernal docs should specify their usage of json schema
- Closes #1513 
Adds a clarification around docs and resources, and recommends that docs specified by third parties which use json schema should specify how they use it.
no
=> docs and resources and external docs

specs/jsonschema-validation.md
Enhancement
- Closes #1572 
Extends the `date-time` format by incorporating time zone information from RFC 9557.
~No~ Yes? `date-time` strings that would have previously failed would now pass.
=> incorporate RFC 9557 time zone extension into 'date-time' format

PROCESS.md, specs/jsonschema-core.md
clarification
- Closes #1569
- Related to #___ 
- Others? 
Adds a new section to help identify requirements for proposals.
It does feel odd to me that the specification is now pointing to a document that could be (and still needs to be) updated.
No.
=> add subsection to point to the github process file for proposal requirements

specs/meta/README.md, specs/meta/meta.json
Update
- Closes #1611 
Updates the meta-schema to disallow unknown keywords while still allowing for extensions.
Also adds a really basic readme to explain how to create extension meta-schemas.  The idea with the readme is to provide at least some foundation for documentation.
=> meta-schema extensions & disallowing unknown keywords

specs/jsonschema-core.md
Resolves #1231 
Replaces #1600 
This is a full rewrite of the Security Considerations sections of the Core spec. It retains most of the original content plus a lot more. The only thing I left out from the original is the part about `$comment`, which I don't think makes sense. If there's an argument for keeping it, I can add it back in.
This new Security Consideration section is inspired by the guidelines and examples in [RFC 3552 - Guidelines for Writing RFC Text on Security Considerations](https://datatracker.ietf.org/doc/html/rfc3552). Some principles I'm trying to follow are,
- This section should not make SHOULD/MUST requirements. Instead, it should state the implications of the requirements made elsewhere in the document.
- This section may discuss threats that are mitigated by spec …
=> New Security Considerations
